/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/batch/v1"
)

// FunctionSpecApplyConfiguration represents a declarative configuration of the FunctionSpec type for use
// with apply.
//
// Specification of a function.
type FunctionSpecApplyConfiguration struct {
	// Version number of this function following the SemVer 2.0.0 specification (see https://semver.org/spec/v2.0.0.html).
	// When label selections are used to specify functions, the version number determines the final function selection if
	// multiple functions have the same labels.
	// Cannot be updated.
	Version *string `json:"version,omitempty"`
	// Describes the Job that will be created when executing this function.
	//
	// The following limitations are imposed:
	// - spec.template.spec.restartPolicy: must be "OnFailure" or "Never". The default is "Never"
	//
	// Cannot be updated.
	// TODO: hinder changes to this field
	Template *v1.JobTemplateSpec `json:"template,omitempty"`
	// Indicates that this function can only run on a local Media Processing Entities (MPE), e.g. if this function changes
	// the Workflow on the management cluster. The default is "false"
	LocalMediaProcessingEntitiesOnly *bool `json:"localMediaProcessingEntitiesOnly,omitempty"`
	// Default configuration values.
	// Cannot be updated.
	// TODO: hinder changes to this field
	DefaultConfig map[string]string `json:"defaultConfig,omitempty"`
}

// FunctionSpecApplyConfiguration constructs a declarative configuration of the FunctionSpec type for use with
// apply.
func FunctionSpec() *FunctionSpecApplyConfiguration {
	return &FunctionSpecApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *FunctionSpecApplyConfiguration) WithVersion(value string) *FunctionSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *FunctionSpecApplyConfiguration) WithTemplate(value v1.JobTemplateSpec) *FunctionSpecApplyConfiguration {
	b.Template = &value
	return b
}

// WithLocalMediaProcessingEntitiesOnly sets the LocalMediaProcessingEntitiesOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalMediaProcessingEntitiesOnly field is set to the value of the last call.
func (b *FunctionSpecApplyConfiguration) WithLocalMediaProcessingEntitiesOnly(value bool) *FunctionSpecApplyConfiguration {
	b.LocalMediaProcessingEntitiesOnly = &value
	return b
}

// WithDefaultConfig puts the entries into the DefaultConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the DefaultConfig field,
// overwriting an existing map entries in DefaultConfig field with the same key.
func (b *FunctionSpecApplyConfiguration) WithDefaultConfig(entries map[string]string) *FunctionSpecApplyConfiguration {
	if b.DefaultConfig == nil && len(entries) > 0 {
		b.DefaultConfig = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.DefaultConfig[k] = v
	}
	return b
}
