/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HTTPAuthConfigApplyConfiguration represents a declarative configuration of the HTTPAuthConfig type for use
// with apply.
//
// Configuration of an HTTP authentication method.
// At most one of these must be set.
type HTTPAuthConfigApplyConfiguration struct {
	// Configures an HTTP basic authentication method.
	Basic *HTTPBasicAuthApplyConfiguration `json:"basic,omitempty"`
	// Configures an HTTP bearer token authentication method.
	Token *HTTPTokenAuthApplyConfiguration `json:"token,omitempty"`
}

// HTTPAuthConfigApplyConfiguration constructs a declarative configuration of the HTTPAuthConfig type for use with
// apply.
func HTTPAuthConfig() *HTTPAuthConfigApplyConfiguration {
	return &HTTPAuthConfigApplyConfiguration{}
}

// WithBasic sets the Basic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Basic field is set to the value of the last call.
func (b *HTTPAuthConfigApplyConfiguration) WithBasic(value *HTTPBasicAuthApplyConfiguration) *HTTPAuthConfigApplyConfiguration {
	b.Basic = value
	return b
}

// WithToken sets the Token field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Token field is set to the value of the last call.
func (b *HTTPAuthConfigApplyConfiguration) WithToken(value *HTTPTokenAuthApplyConfiguration) *HTTPAuthConfigApplyConfiguration {
	b.Token = value
	return b
}
