/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	meta "github.com/nagare-media/engine/pkg/apis/meta"
)

// HTTPTokenAuthApplyConfiguration represents a declarative configuration of the HTTPTokenAuth type for use
// with apply.
//
// Configuration of an HTTP bearer token authentication method.
type HTTPTokenAuthApplyConfiguration struct {
	// Reference to a Secret that contains the key "token". Only references to Secrets are allowed. A MediaLocation can
	// only reference Secrets from its own Namespace.
	SecretRef *meta.ConfigMapOrSecretReference `json:"secretRef,omitempty"`
	// Name of the HTTP header the token should be passed to. The default is "Authorization".
	HeaderName *string `json:"headerName,omitempty"`
	// Prefix of the HTTP header value before the token. The default is "Bearer".
	HeaderValuePrefix *string `json:"headerValuePrefix,omitempty"`
}

// HTTPTokenAuthApplyConfiguration constructs a declarative configuration of the HTTPTokenAuth type for use with
// apply.
func HTTPTokenAuth() *HTTPTokenAuthApplyConfiguration {
	return &HTTPTokenAuthApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *HTTPTokenAuthApplyConfiguration) WithSecretRef(value meta.ConfigMapOrSecretReference) *HTTPTokenAuthApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithHeaderName sets the HeaderName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeaderName field is set to the value of the last call.
func (b *HTTPTokenAuthApplyConfiguration) WithHeaderName(value string) *HTTPTokenAuthApplyConfiguration {
	b.HeaderName = &value
	return b
}

// WithHeaderValuePrefix sets the HeaderValuePrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeaderValuePrefix field is set to the value of the last call.
func (b *HTTPTokenAuthApplyConfiguration) WithHeaderValuePrefix(value string) *HTTPTokenAuthApplyConfiguration {
	b.HeaderValuePrefix = &value
	return b
}
