/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MediaCodecApplyConfiguration represents a declarative configuration of the MediaCodec type for use
// with apply.
type MediaCodecApplyConfiguration struct {
	Name    *string `json:"name,omitempty"`
	Profile *string `json:"profile,omitempty"`
	Level   *string `json:"level,omitempty"`
}

// MediaCodecApplyConfiguration constructs a declarative configuration of the MediaCodec type for use with
// apply.
func MediaCodec() *MediaCodecApplyConfiguration {
	return &MediaCodecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MediaCodecApplyConfiguration) WithName(value string) *MediaCodecApplyConfiguration {
	b.Name = &value
	return b
}

// WithProfile sets the Profile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Profile field is set to the value of the last call.
func (b *MediaCodecApplyConfiguration) WithProfile(value string) *MediaCodecApplyConfiguration {
	b.Profile = &value
	return b
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *MediaCodecApplyConfiguration) WithLevel(value string) *MediaCodecApplyConfiguration {
	b.Level = &value
	return b
}
