/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nagare-media/engine/api/v1alpha1"
)

// MediaStreamTypeApplyConfiguration represents a declarative configuration of the MediaStreamType type for use
// with apply.
type MediaStreamTypeApplyConfiguration struct {
	Audio    *AudioMediaStreamApplyConfiguration    `json:"audio,omitempty"`
	Video    *VideoMediaStreamApplyConfiguration    `json:"video,omitempty"`
	Subtitle *SubtitleMediaStreamApplyConfiguration `json:"subtitle,omitempty"`
	Data     *apiv1alpha1.DataMediaStream           `json:"data,omitempty"`
}

// MediaStreamTypeApplyConfiguration constructs a declarative configuration of the MediaStreamType type for use with
// apply.
func MediaStreamType() *MediaStreamTypeApplyConfiguration {
	return &MediaStreamTypeApplyConfiguration{}
}

// WithAudio sets the Audio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audio field is set to the value of the last call.
func (b *MediaStreamTypeApplyConfiguration) WithAudio(value *AudioMediaStreamApplyConfiguration) *MediaStreamTypeApplyConfiguration {
	b.Audio = value
	return b
}

// WithVideo sets the Video field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Video field is set to the value of the last call.
func (b *MediaStreamTypeApplyConfiguration) WithVideo(value *VideoMediaStreamApplyConfiguration) *MediaStreamTypeApplyConfiguration {
	b.Video = value
	return b
}

// WithSubtitle sets the Subtitle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subtitle field is set to the value of the last call.
func (b *MediaStreamTypeApplyConfiguration) WithSubtitle(value *SubtitleMediaStreamApplyConfiguration) *MediaStreamTypeApplyConfiguration {
	b.Subtitle = value
	return b
}

// WithData sets the Data field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Data field is set to the value of the last call.
func (b *MediaStreamTypeApplyConfiguration) WithData(value apiv1alpha1.DataMediaStream) *MediaStreamTypeApplyConfiguration {
	b.Data = &value
	return b
}
