/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MediaProcessingEntityStatusApplyConfiguration represents a declarative configuration of the MediaProcessingEntityStatus type for use
// with apply.
//
// Status of a MediaProcessingEntity
type MediaProcessingEntityStatusApplyConfiguration struct {
	// The latest available observations of an object's current state. When a connection to a MediaProcessingEntity is
	// established, one of the conditions will have type "Ready" and status true.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
	// A human readable message indicating why the MediaProcessingEntity is in this condition.
	Message *string `json:"message,omitempty"`
}

// MediaProcessingEntityStatusApplyConfiguration constructs a declarative configuration of the MediaProcessingEntityStatus type for use with
// apply.
func MediaProcessingEntityStatus() *MediaProcessingEntityStatusApplyConfiguration {
	return &MediaProcessingEntityStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MediaProcessingEntityStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *MediaProcessingEntityStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *MediaProcessingEntityStatusApplyConfiguration) WithMessage(value string) *MediaProcessingEntityStatusApplyConfiguration {
	b.Message = &value
	return b
}
