/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MediaProcessingEntityConfigApplyConfiguration represents a declarative configuration of the MediaProcessingEntityConfig type for use
// with apply.
//
// Configuration of the Media Processing Entity (MPE).
// Exactly one of these must be set.
type MediaProcessingEntityConfigApplyConfiguration struct {
	// Configures the Media Processing Entity (MPE) to talk to the local Kubernetes cluster.
	Local *LocalMediaProcessingEntityApplyConfiguration `json:"local,omitempty"`
	// Configures the Media Processing Entity (MPE) to talk to a remote Kubernetes cluster.
	Remote *RemoteMediaProcessingEntityApplyConfiguration `json:"remote,omitempty"`
}

// MediaProcessingEntityConfigApplyConfiguration constructs a declarative configuration of the MediaProcessingEntityConfig type for use with
// apply.
func MediaProcessingEntityConfig() *MediaProcessingEntityConfigApplyConfiguration {
	return &MediaProcessingEntityConfigApplyConfiguration{}
}

// WithLocal sets the Local field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Local field is set to the value of the last call.
func (b *MediaProcessingEntityConfigApplyConfiguration) WithLocal(value *LocalMediaProcessingEntityApplyConfiguration) *MediaProcessingEntityConfigApplyConfiguration {
	b.Local = value
	return b
}

// WithRemote sets the Remote field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Remote field is set to the value of the last call.
func (b *MediaProcessingEntityConfigApplyConfiguration) WithRemote(value *RemoteMediaProcessingEntityApplyConfiguration) *MediaProcessingEntityConfigApplyConfiguration {
	b.Remote = value
	return b
}
