/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nagare-media/engine/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MediaStreamApplyConfiguration represents a declarative configuration of the MediaStream type for use
// with apply.
type MediaStreamApplyConfiguration struct {
	ID    *string                       `json:"id,omitempty"`
	Codec *MediaCodecApplyConfiguration `json:"codec,omitempty"`
	// BitRate in bit/s
	BitRate  *apiv1alpha1.BitRate `json:"bitRate,omitempty"`
	Duration *v1.Duration         `json:"duration,omitempty"`
	// Properties additionally associated with this stream.
	Properties                        []MediaPropertyApplyConfiguration `json:"properties,omitempty"`
	MediaStreamTypeApplyConfiguration `json:",inline"`
}

// MediaStreamApplyConfiguration constructs a declarative configuration of the MediaStream type for use with
// apply.
func MediaStream() *MediaStreamApplyConfiguration {
	return &MediaStreamApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *MediaStreamApplyConfiguration) WithID(value string) *MediaStreamApplyConfiguration {
	b.ID = &value
	return b
}

// WithCodec sets the Codec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Codec field is set to the value of the last call.
func (b *MediaStreamApplyConfiguration) WithCodec(value *MediaCodecApplyConfiguration) *MediaStreamApplyConfiguration {
	b.Codec = value
	return b
}

// WithBitRate sets the BitRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BitRate field is set to the value of the last call.
func (b *MediaStreamApplyConfiguration) WithBitRate(value apiv1alpha1.BitRate) *MediaStreamApplyConfiguration {
	b.BitRate = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *MediaStreamApplyConfiguration) WithDuration(value v1.Duration) *MediaStreamApplyConfiguration {
	b.Duration = &value
	return b
}

// WithProperties adds the given value to the Properties field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Properties field.
func (b *MediaStreamApplyConfiguration) WithProperties(values ...*MediaPropertyApplyConfiguration) *MediaStreamApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProperties")
		}
		b.Properties = append(b.Properties, *values[i])
	}
	return b
}

// WithAudio sets the Audio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audio field is set to the value of the last call.
func (b *MediaStreamApplyConfiguration) WithAudio(value *AudioMediaStreamApplyConfiguration) *MediaStreamApplyConfiguration {
	b.MediaStreamTypeApplyConfiguration.Audio = value
	return b
}

// WithVideo sets the Video field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Video field is set to the value of the last call.
func (b *MediaStreamApplyConfiguration) WithVideo(value *VideoMediaStreamApplyConfiguration) *MediaStreamApplyConfiguration {
	b.MediaStreamTypeApplyConfiguration.Video = value
	return b
}

// WithSubtitle sets the Subtitle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subtitle field is set to the value of the last call.
func (b *MediaStreamApplyConfiguration) WithSubtitle(value *SubtitleMediaStreamApplyConfiguration) *MediaStreamApplyConfiguration {
	b.MediaStreamTypeApplyConfiguration.Subtitle = value
	return b
}

// WithData sets the Data field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Data field is set to the value of the last call.
func (b *MediaStreamApplyConfiguration) WithData(value apiv1alpha1.DataMediaStream) *MediaStreamApplyConfiguration {
	b.MediaStreamTypeApplyConfiguration.Data = &value
	return b
}
