/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nagare-media/engine/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MediaMetadataApplyConfiguration represents a declarative configuration of the MediaMetadata type for use
// with apply.
type MediaMetadataApplyConfiguration struct {
	MimeType  *apiv1alpha1.MimeType  `json:"mimeType,omitempty"`
	CodecType *apiv1alpha1.CodecType `json:"codecType,omitempty"`
	Duration  *v1.Duration           `json:"duration,omitempty"`
	// BitRate in bit/s
	BitRate *apiv1alpha1.BitRate `json:"bitRate,omitempty"`
	// Size in bytes.
	Size      *apiv1alpha1.Size                 `json:"size,omitempty"`
	Checksums []ChecksumApplyConfiguration      `json:"checksums,omitempty"`
	Container *MediaContainerApplyConfiguration `json:"container,omitempty"`
	Streams   []MediaStreamApplyConfiguration   `json:"streams,omitempty"`
}

// MediaMetadataApplyConfiguration constructs a declarative configuration of the MediaMetadata type for use with
// apply.
func MediaMetadata() *MediaMetadataApplyConfiguration {
	return &MediaMetadataApplyConfiguration{}
}

// WithMimeType sets the MimeType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MimeType field is set to the value of the last call.
func (b *MediaMetadataApplyConfiguration) WithMimeType(value apiv1alpha1.MimeType) *MediaMetadataApplyConfiguration {
	b.MimeType = &value
	return b
}

// WithCodecType sets the CodecType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CodecType field is set to the value of the last call.
func (b *MediaMetadataApplyConfiguration) WithCodecType(value apiv1alpha1.CodecType) *MediaMetadataApplyConfiguration {
	b.CodecType = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *MediaMetadataApplyConfiguration) WithDuration(value v1.Duration) *MediaMetadataApplyConfiguration {
	b.Duration = &value
	return b
}

// WithBitRate sets the BitRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BitRate field is set to the value of the last call.
func (b *MediaMetadataApplyConfiguration) WithBitRate(value apiv1alpha1.BitRate) *MediaMetadataApplyConfiguration {
	b.BitRate = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *MediaMetadataApplyConfiguration) WithSize(value apiv1alpha1.Size) *MediaMetadataApplyConfiguration {
	b.Size = &value
	return b
}

// WithChecksums adds the given value to the Checksums field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Checksums field.
func (b *MediaMetadataApplyConfiguration) WithChecksums(values ...*ChecksumApplyConfiguration) *MediaMetadataApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithChecksums")
		}
		b.Checksums = append(b.Checksums, *values[i])
	}
	return b
}

// WithContainer sets the Container field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Container field is set to the value of the last call.
func (b *MediaMetadataApplyConfiguration) WithContainer(value *MediaContainerApplyConfiguration) *MediaMetadataApplyConfiguration {
	b.Container = value
	return b
}

// WithStreams adds the given value to the Streams field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Streams field.
func (b *MediaMetadataApplyConfiguration) WithStreams(values ...*MediaStreamApplyConfiguration) *MediaMetadataApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithStreams")
		}
		b.Streams = append(b.Streams, *values[i])
	}
	return b
}
