/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MediaLocationConfigApplyConfiguration represents a declarative configuration of the MediaLocationConfig type for use
// with apply.
//
// Configuration of a media location.
// Exactly one of these must be set.
type MediaLocationConfigApplyConfiguration struct {
	// Configures an HTTP media location.
	// This media location can be used between NBMP tasks that use the "step" execution mode.
	HTTP *HTTPMediaLocationApplyConfiguration `json:"http,omitempty"`
	// Configures an S3 media location.
	// This media location can be used between NBMP tasks that use the "step" execution mode.
	S3 *S3MediaLocationApplyConfiguration `json:"s3,omitempty"`
	// Configures an Opencast media location.
	// This media location can be used between NBMP tasks that use the "step" execution mode.
	Opencast *OpencastMediaLocationApplyConfiguration `json:"opencast,omitempty"`
	// Configures an RTMP media location.
	// This media location can be used between NBMP tasks that use the "streaming" execution mode.
	RTMP *RTMPMediaLocationApplyConfiguration `json:"rtmp,omitempty"`
	// Configures an RTSP media location.
	// This media location can be used between NBMP tasks that use the "streaming" execution mode.
	RTSP *RTSPMediaLocationApplyConfiguration `json:"rtsp,omitempty"`
	// Configures a RIST media location.
	// This media location can be used between NBMP tasks that use the "streaming" execution mode.
	RIST *RISTMediaLocationApplyConfiguration `json:"rist,omitempty"`
}

// MediaLocationConfigApplyConfiguration constructs a declarative configuration of the MediaLocationConfig type for use with
// apply.
func MediaLocationConfig() *MediaLocationConfigApplyConfiguration {
	return &MediaLocationConfigApplyConfiguration{}
}

// WithHTTP sets the HTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP field is set to the value of the last call.
func (b *MediaLocationConfigApplyConfiguration) WithHTTP(value *HTTPMediaLocationApplyConfiguration) *MediaLocationConfigApplyConfiguration {
	b.HTTP = value
	return b
}

// WithS3 sets the S3 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3 field is set to the value of the last call.
func (b *MediaLocationConfigApplyConfiguration) WithS3(value *S3MediaLocationApplyConfiguration) *MediaLocationConfigApplyConfiguration {
	b.S3 = value
	return b
}

// WithOpencast sets the Opencast field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Opencast field is set to the value of the last call.
func (b *MediaLocationConfigApplyConfiguration) WithOpencast(value *OpencastMediaLocationApplyConfiguration) *MediaLocationConfigApplyConfiguration {
	b.Opencast = value
	return b
}

// WithRTMP sets the RTMP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RTMP field is set to the value of the last call.
func (b *MediaLocationConfigApplyConfiguration) WithRTMP(value *RTMPMediaLocationApplyConfiguration) *MediaLocationConfigApplyConfiguration {
	b.RTMP = value
	return b
}

// WithRTSP sets the RTSP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RTSP field is set to the value of the last call.
func (b *MediaLocationConfigApplyConfiguration) WithRTSP(value *RTSPMediaLocationApplyConfiguration) *MediaLocationConfigApplyConfiguration {
	b.RTSP = value
	return b
}

// WithRIST sets the RIST field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RIST field is set to the value of the last call.
func (b *MediaLocationConfigApplyConfiguration) WithRIST(value *RISTMediaLocationApplyConfiguration) *MediaLocationConfigApplyConfiguration {
	b.RIST = value
	return b
}
