/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nagare-media/engine/api/v1alpha1"
	base "github.com/nagare-media/models.go/base"
)

// MediaApplyConfiguration represents a declarative configuration of the Media type for use
// with apply.
//
// Media describes an input or output.
type MediaApplyConfiguration struct {
	// ID of this media.
	ID *string `json:"id,omitempty"`
	// Human readable description of this media.
	HumanReadable *HumanReadableMediaDescriptionApplyConfiguration `json:"humanReadable,omitempty"`
	// Type of this media.
	Type *apiv1alpha1.MediaType `json:"type,omitempty"`
	// Direction this media is streamed in.
	Direction *apiv1alpha1.MediaDirection `json:"direction,omitempty"`
	// URL of this media.
	URL *base.URI `json:"url,omitempty"`
	// Labels of this media.
	Labels map[string]string `json:"labels,omitempty"`
	// Metadata of this media.
	Metadata *MediaMetadataApplyConfiguration `json:"metadata,omitempty"`
}

// MediaApplyConfiguration constructs a declarative configuration of the Media type for use with
// apply.
func Media() *MediaApplyConfiguration {
	return &MediaApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *MediaApplyConfiguration) WithID(value string) *MediaApplyConfiguration {
	b.ID = &value
	return b
}

// WithHumanReadable sets the HumanReadable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HumanReadable field is set to the value of the last call.
func (b *MediaApplyConfiguration) WithHumanReadable(value *HumanReadableMediaDescriptionApplyConfiguration) *MediaApplyConfiguration {
	b.HumanReadable = value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *MediaApplyConfiguration) WithType(value apiv1alpha1.MediaType) *MediaApplyConfiguration {
	b.Type = &value
	return b
}

// WithDirection sets the Direction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Direction field is set to the value of the last call.
func (b *MediaApplyConfiguration) WithDirection(value apiv1alpha1.MediaDirection) *MediaApplyConfiguration {
	b.Direction = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *MediaApplyConfiguration) WithURL(value base.URI) *MediaApplyConfiguration {
	b.URL = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *MediaApplyConfiguration) WithLabels(entries map[string]string) *MediaApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *MediaApplyConfiguration) WithMetadata(value *MediaMetadataApplyConfiguration) *MediaApplyConfiguration {
	b.Metadata = value
	return b
}
