/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// OutputPortBindingApplyConfiguration represents a declarative configuration of the OutputPortBinding type for use
// with apply.
type OutputPortBindingApplyConfiguration struct {
	// ID of the port.
	ID *string `json:"id,omitempty"`
	// Output binding.
	Output *MediaApplyConfiguration `json:"output,omitempty"`
}

// OutputPortBindingApplyConfiguration constructs a declarative configuration of the OutputPortBinding type for use with
// apply.
func OutputPortBinding() *OutputPortBindingApplyConfiguration {
	return &OutputPortBindingApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *OutputPortBindingApplyConfiguration) WithID(value string) *OutputPortBindingApplyConfiguration {
	b.ID = &value
	return b
}

// WithOutput sets the Output field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Output field is set to the value of the last call.
func (b *OutputPortBindingApplyConfiguration) WithOutput(value *MediaApplyConfiguration) *OutputPortBindingApplyConfiguration {
	b.Output = value
	return b
}
