/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// QueryArgApplyConfiguration represents a declarative configuration of the QueryArg type for use
// with apply.
//
// Specifies a URL query argument.
type QueryArgApplyConfiguration struct {
	// Name of the query argument.
	Name *string `json:"name,omitempty"`
	// Value of the query argument. This field is required if valueFrom is not specified. If both are specified, value has
	// precedence.
	Value *string `json:"value,omitempty"`
}

// QueryArgApplyConfiguration constructs a declarative configuration of the QueryArg type for use with
// apply.
func QueryArg() *QueryArgApplyConfiguration {
	return &QueryArgApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *QueryArgApplyConfiguration) WithName(value string) *QueryArgApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *QueryArgApplyConfiguration) WithValue(value string) *QueryArgApplyConfiguration {
	b.Value = &value
	return b
}
