/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RISTMediaLocationApplyConfiguration represents a declarative configuration of the RISTMediaLocation type for use
// with apply.
//
// Configuration of a RIST media location.
type RISTMediaLocationApplyConfiguration struct {
	// RIST base URL. Media referencing this location are relative to this URL.
	BaseURL *string `json:"baseURL,omitempty"`
	// RIST profile to use. The default is "main".
	Profile *string `json:"profile,omitempty"`
	// Sets the buffer size. The maximum duration is 30s.
	BufferSize *v1.Duration `json:"bufferSize,omitempty"`
	// RIST encryption configuration.
	Encryption *RISTEncryptionApplyConfiguration `json:"encryption,omitempty"`
}

// RISTMediaLocationApplyConfiguration constructs a declarative configuration of the RISTMediaLocation type for use with
// apply.
func RISTMediaLocation() *RISTMediaLocationApplyConfiguration {
	return &RISTMediaLocationApplyConfiguration{}
}

// WithBaseURL sets the BaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseURL field is set to the value of the last call.
func (b *RISTMediaLocationApplyConfiguration) WithBaseURL(value string) *RISTMediaLocationApplyConfiguration {
	b.BaseURL = &value
	return b
}

// WithProfile sets the Profile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Profile field is set to the value of the last call.
func (b *RISTMediaLocationApplyConfiguration) WithProfile(value string) *RISTMediaLocationApplyConfiguration {
	b.Profile = &value
	return b
}

// WithBufferSize sets the BufferSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BufferSize field is set to the value of the last call.
func (b *RISTMediaLocationApplyConfiguration) WithBufferSize(value v1.Duration) *RISTMediaLocationApplyConfiguration {
	b.BufferSize = &value
	return b
}

// WithEncryption sets the Encryption field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Encryption field is set to the value of the last call.
func (b *RISTMediaLocationApplyConfiguration) WithEncryption(value *RISTEncryptionApplyConfiguration) *RISTMediaLocationApplyConfiguration {
	b.Encryption = value
	return b
}
