/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	meta "github.com/nagare-media/engine/pkg/apis/meta"
)

// RTMPBasicAuthApplyConfiguration represents a declarative configuration of the RTMPBasicAuth type for use
// with apply.
//
// Configuration of an RTMP basic authentication method.
type RTMPBasicAuthApplyConfiguration struct {
	// Reference to a Secret that contains the keys "username" and "password". Only references to Secrets are allowed. A
	// MediaLocation can only reference Secrets from its own Namespace.
	SecretRef *meta.ConfigMapOrSecretReference `json:"secretRef,omitempty"`
}

// RTMPBasicAuthApplyConfiguration constructs a declarative configuration of the RTMPBasicAuth type for use with
// apply.
func RTMPBasicAuth() *RTMPBasicAuthApplyConfiguration {
	return &RTMPBasicAuthApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *RTMPBasicAuthApplyConfiguration) WithSecretRef(value meta.ConfigMapOrSecretReference) *RTMPBasicAuthApplyConfiguration {
	b.SecretRef = &value
	return b
}
