/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RTMPMediaLocationApplyConfiguration represents a declarative configuration of the RTMPMediaLocation type for use
// with apply.
//
// Configuration of an RTMP media location.
type RTMPMediaLocationApplyConfiguration struct {
	// RTMP base URL. Media referencing this location are relative to this URL.
	BaseURL *string `json:"baseURL,omitempty"`
	// The RTMP application name. This overwrites application names given through baseURL.
	App *string `json:"app,omitempty"`
	// List of RTMP query arguments that should be send with RTMP requests.
	// Note that it is up the the function implementation to honor these query arguments.
	QueryArgs []QueryArgApplyConfiguration `json:"queryArgs,omitempty"`
	// RTMP authentication configuration.
	Auth *RTMPAuthConfigApplyConfiguration `json:"auth,omitempty"`
}

// RTMPMediaLocationApplyConfiguration constructs a declarative configuration of the RTMPMediaLocation type for use with
// apply.
func RTMPMediaLocation() *RTMPMediaLocationApplyConfiguration {
	return &RTMPMediaLocationApplyConfiguration{}
}

// WithBaseURL sets the BaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseURL field is set to the value of the last call.
func (b *RTMPMediaLocationApplyConfiguration) WithBaseURL(value string) *RTMPMediaLocationApplyConfiguration {
	b.BaseURL = &value
	return b
}

// WithApp sets the App field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the App field is set to the value of the last call.
func (b *RTMPMediaLocationApplyConfiguration) WithApp(value string) *RTMPMediaLocationApplyConfiguration {
	b.App = &value
	return b
}

// WithQueryArgs adds the given value to the QueryArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the QueryArgs field.
func (b *RTMPMediaLocationApplyConfiguration) WithQueryArgs(values ...*QueryArgApplyConfiguration) *RTMPMediaLocationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithQueryArgs")
		}
		b.QueryArgs = append(b.QueryArgs, *values[i])
	}
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *RTMPMediaLocationApplyConfiguration) WithAuth(value *RTMPAuthConfigApplyConfiguration) *RTMPMediaLocationApplyConfiguration {
	b.Auth = value
	return b
}
