/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RTSPMediaLocationApplyConfiguration represents a declarative configuration of the RTSPMediaLocation type for use
// with apply.
//
// Configuration of an RTSP media location.
type RTSPMediaLocationApplyConfiguration struct {
	// RTSP base URL. Media referencing this location are relative to this URL.
	BaseURL *string `json:"baseURL,omitempty"`
	// Forces a specific transport protocol. The default is "auto" which tries detecting the best transport protocol
	// automatically.
	TransportProtocol *string `json:"transportProtocol,omitempty"`
	// List of RTSP query arguments that should be send with RTSP requests.
	// Note that it is up the the function implementation to honor these query arguments.
	QueryArgs []QueryArgApplyConfiguration `json:"queryArgs,omitempty"`
	// RTSP authentication configuration.
	Auth *RTSPAuthConfigApplyConfiguration `json:"auth,omitempty"`
}

// RTSPMediaLocationApplyConfiguration constructs a declarative configuration of the RTSPMediaLocation type for use with
// apply.
func RTSPMediaLocation() *RTSPMediaLocationApplyConfiguration {
	return &RTSPMediaLocationApplyConfiguration{}
}

// WithBaseURL sets the BaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseURL field is set to the value of the last call.
func (b *RTSPMediaLocationApplyConfiguration) WithBaseURL(value string) *RTSPMediaLocationApplyConfiguration {
	b.BaseURL = &value
	return b
}

// WithTransportProtocol sets the TransportProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TransportProtocol field is set to the value of the last call.
func (b *RTSPMediaLocationApplyConfiguration) WithTransportProtocol(value string) *RTSPMediaLocationApplyConfiguration {
	b.TransportProtocol = &value
	return b
}

// WithQueryArgs adds the given value to the QueryArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the QueryArgs field.
func (b *RTSPMediaLocationApplyConfiguration) WithQueryArgs(values ...*QueryArgApplyConfiguration) *RTSPMediaLocationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithQueryArgs")
		}
		b.QueryArgs = append(b.QueryArgs, *values[i])
	}
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *RTSPMediaLocationApplyConfiguration) WithAuth(value *RTSPAuthConfigApplyConfiguration) *RTSPMediaLocationApplyConfiguration {
	b.Auth = value
	return b
}
