/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RTSPAuthConfigApplyConfiguration represents a declarative configuration of the RTSPAuthConfig type for use
// with apply.
//
// Configuration of an RTSP authentication method.
// At most one of these must be set.
type RTSPAuthConfigApplyConfiguration struct {
	// Configures an RTSP basic authentication method.
	Basic *RTSPBasicAuthApplyConfiguration `json:"basic,omitempty"`
}

// RTSPAuthConfigApplyConfiguration constructs a declarative configuration of the RTSPAuthConfig type for use with
// apply.
func RTSPAuthConfig() *RTSPAuthConfigApplyConfiguration {
	return &RTSPAuthConfigApplyConfiguration{}
}

// WithBasic sets the Basic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Basic field is set to the value of the last call.
func (b *RTSPAuthConfigApplyConfiguration) WithBasic(value *RTSPBasicAuthApplyConfiguration) *RTSPAuthConfigApplyConfiguration {
	b.Basic = value
	return b
}
