/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// S3MediaLocationApplyConfiguration represents a declarative configuration of the S3MediaLocation type for use
// with apply.
//
// Configuration of an S3 media location.
type S3MediaLocationApplyConfiguration struct {
	// Name of the S3 bucket.
	Bucket *string `json:"bucket,omitempty"`
	// Region of the S3 bucket.
	Region *string `json:"region,omitempty"`
	// S3 authentication configuration.
	Auth *S3AuthConfigApplyConfiguration `json:"auth,omitempty"`
	// Custom endpoint URL to send S3 requests to.
	EndpointURL *string `json:"endpointURL,omitempty"`
	// Whether to use path-style URLs to access S3. By default virtual-hosted–style is used.
	UsePathStyle *bool `json:"usePathStyle,omitempty"`
}

// S3MediaLocationApplyConfiguration constructs a declarative configuration of the S3MediaLocation type for use with
// apply.
func S3MediaLocation() *S3MediaLocationApplyConfiguration {
	return &S3MediaLocationApplyConfiguration{}
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *S3MediaLocationApplyConfiguration) WithBucket(value string) *S3MediaLocationApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *S3MediaLocationApplyConfiguration) WithRegion(value string) *S3MediaLocationApplyConfiguration {
	b.Region = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *S3MediaLocationApplyConfiguration) WithAuth(value *S3AuthConfigApplyConfiguration) *S3MediaLocationApplyConfiguration {
	b.Auth = value
	return b
}

// WithEndpointURL sets the EndpointURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndpointURL field is set to the value of the last call.
func (b *S3MediaLocationApplyConfiguration) WithEndpointURL(value string) *S3MediaLocationApplyConfiguration {
	b.EndpointURL = &value
	return b
}

// WithUsePathStyle sets the UsePathStyle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsePathStyle field is set to the value of the last call.
func (b *S3MediaLocationApplyConfiguration) WithUsePathStyle(value bool) *S3MediaLocationApplyConfiguration {
	b.UsePathStyle = &value
	return b
}
