/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nagare-media/engine/api/v1alpha1"
	meta "github.com/nagare-media/engine/pkg/apis/meta"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TaskStatusApplyConfiguration represents a declarative configuration of the TaskStatus type for use
// with apply.
//
// Status of a Task.
type TaskStatusApplyConfiguration struct {
	// The status of this Task.
	Phase *apiv1alpha1.TaskPhase `json:"phase,omitempty"`
	// The latest available observations of an object's current state. When a Task fails, one of the conditions will have
	// type "Failed" and status true. When a Task is completed, one of the conditions will have type "Complete" and status
	// true.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
	// A human readable message indicating why the Task is in this condition.
	Message *string `json:"message,omitempty"`
	// Represents time when the Task controller first started processing a Task. It is represented in RFC3339 form and is
	// in UTC.
	QueuedTime *v1.Time `json:"queuedTime,omitempty"`
	// Represents time when the Task controller transitioned to the "running" phase. It is represented in RFC3339 form and
	// is in UTC.
	StartTime *v1.Time `json:"startTime,omitempty"`
	// Represents time when the Task has ended processing (either failed or completed). It is not guaranteed to be set in
	// happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
	EndTime *v1.Time `json:"endTime,omitempty"`
	// Reference to the selected MediaProcessingEntity.
	MediaProcessingEntityRef *meta.ObjectReference `json:"mediaProcessingEntityRef,omitempty"`
	// Reference to the selected Function.
	FunctionRef *meta.ObjectReference `json:"functionRef,omitempty"`
	// Reference to the Job.
	JobRef *meta.ExactObjectReference `json:"jobRef,omitempty"`
}

// TaskStatusApplyConfiguration constructs a declarative configuration of the TaskStatus type for use with
// apply.
func TaskStatus() *TaskStatusApplyConfiguration {
	return &TaskStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithPhase(value apiv1alpha1.TaskPhase) *TaskStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TaskStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *TaskStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithMessage(value string) *TaskStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithQueuedTime sets the QueuedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QueuedTime field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithQueuedTime(value v1.Time) *TaskStatusApplyConfiguration {
	b.QueuedTime = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithStartTime(value v1.Time) *TaskStatusApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithEndTime sets the EndTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndTime field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithEndTime(value v1.Time) *TaskStatusApplyConfiguration {
	b.EndTime = &value
	return b
}

// WithMediaProcessingEntityRef sets the MediaProcessingEntityRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MediaProcessingEntityRef field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithMediaProcessingEntityRef(value meta.ObjectReference) *TaskStatusApplyConfiguration {
	b.MediaProcessingEntityRef = &value
	return b
}

// WithFunctionRef sets the FunctionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FunctionRef field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithFunctionRef(value meta.ObjectReference) *TaskStatusApplyConfiguration {
	b.FunctionRef = &value
	return b
}

// WithJobRef sets the JobRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobRef field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithJobRef(value meta.ExactObjectReference) *TaskStatusApplyConfiguration {
	b.JobRef = &value
	return b
}
