/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	meta "github.com/nagare-media/engine/pkg/apis/meta"
	batchv1 "k8s.io/api/batch/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TaskTemplateSpecApplyConfiguration represents a declarative configuration of the TaskTemplateSpec type for use
// with apply.
//
// TaskTemplateSpec defines the desired state of TaskTemplate
type TaskTemplateSpecApplyConfiguration struct {
	// Human readable description of this task.
	HumanReadable *HumanReadableTaskDescriptionApplyConfiguration `json:"humanReadable,omitempty"`
	// Reference to a MediaProcessingEntity or ClusterMediaProcessingEntity. Only references to these two kinds are
	// allowed. A TaskTemplate can only reference MediaProcessingEntities from its own Namespace.
	MediaProcessingEntityRef *meta.LocalObjectReference `json:"mediaProcessingEntityRef,omitempty"`
	// Label selector for a MediaProcessingEntity or ClusterMediaProcessingEntity. MediaProcessingEntity has precedence
	// over ClusterMediaProcessingEntity. If multiple Media Processing Entities are selected, the newest one is chosen.
	MediaProcessingEntitySelector *v1.LabelSelectorApplyConfiguration `json:"mediaProcessingEntitySelector,omitempty"`
	// Reference to a Function or ClusterFunction. Only references to these two kinds are allowed. A TaskTemplate can only
	// reference Functions from its own Namespace.
	FunctionRef *meta.LocalObjectReference `json:"functionRef,omitempty"`
	// Label selector for a Function or ClusterFunction. Function has precedence over ClusterFunction. If multiple
	// Functions are selected, the Function with the newest version is chosen.
	FunctionSelector *v1.LabelSelectorApplyConfiguration `json:"functionSelector,omitempty"`
	// Patches applied to the Job template description of the Function.
	//
	// Cannot be updated.
	// TODO: hinder changes to this field
	TemplatePatches *batchv1.JobTemplateSpec `json:"templatePatches,omitempty"`
	// Policy for dealing with a failed Job resulting from this Task. Conditions for when a Job is considered as failure
	// are defined in the templates `jobFailurePolicy` field.
	JobFailurePolicy *JobFailurePolicyApplyConfiguration `json:"jobFailurePolicy,omitempty"`
	// Configuration values.
	Config map[string]string `json:"config,omitempty"`
}

// TaskTemplateSpecApplyConfiguration constructs a declarative configuration of the TaskTemplateSpec type for use with
// apply.
func TaskTemplateSpec() *TaskTemplateSpecApplyConfiguration {
	return &TaskTemplateSpecApplyConfiguration{}
}

// WithHumanReadable sets the HumanReadable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HumanReadable field is set to the value of the last call.
func (b *TaskTemplateSpecApplyConfiguration) WithHumanReadable(value *HumanReadableTaskDescriptionApplyConfiguration) *TaskTemplateSpecApplyConfiguration {
	b.HumanReadable = value
	return b
}

// WithMediaProcessingEntityRef sets the MediaProcessingEntityRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MediaProcessingEntityRef field is set to the value of the last call.
func (b *TaskTemplateSpecApplyConfiguration) WithMediaProcessingEntityRef(value meta.LocalObjectReference) *TaskTemplateSpecApplyConfiguration {
	b.MediaProcessingEntityRef = &value
	return b
}

// WithMediaProcessingEntitySelector sets the MediaProcessingEntitySelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MediaProcessingEntitySelector field is set to the value of the last call.
func (b *TaskTemplateSpecApplyConfiguration) WithMediaProcessingEntitySelector(value *v1.LabelSelectorApplyConfiguration) *TaskTemplateSpecApplyConfiguration {
	b.MediaProcessingEntitySelector = value
	return b
}

// WithFunctionRef sets the FunctionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FunctionRef field is set to the value of the last call.
func (b *TaskTemplateSpecApplyConfiguration) WithFunctionRef(value meta.LocalObjectReference) *TaskTemplateSpecApplyConfiguration {
	b.FunctionRef = &value
	return b
}

// WithFunctionSelector sets the FunctionSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FunctionSelector field is set to the value of the last call.
func (b *TaskTemplateSpecApplyConfiguration) WithFunctionSelector(value *v1.LabelSelectorApplyConfiguration) *TaskTemplateSpecApplyConfiguration {
	b.FunctionSelector = value
	return b
}

// WithTemplatePatches sets the TemplatePatches field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplatePatches field is set to the value of the last call.
func (b *TaskTemplateSpecApplyConfiguration) WithTemplatePatches(value batchv1.JobTemplateSpec) *TaskTemplateSpecApplyConfiguration {
	b.TemplatePatches = &value
	return b
}

// WithJobFailurePolicy sets the JobFailurePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobFailurePolicy field is set to the value of the last call.
func (b *TaskTemplateSpecApplyConfiguration) WithJobFailurePolicy(value *JobFailurePolicyApplyConfiguration) *TaskTemplateSpecApplyConfiguration {
	b.JobFailurePolicy = value
	return b
}

// WithConfig puts the entries into the Config field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Config field,
// overwriting an existing map entries in Config field with the same key.
func (b *TaskTemplateSpecApplyConfiguration) WithConfig(entries map[string]string) *TaskTemplateSpecApplyConfiguration {
	if b.Config == nil && len(entries) > 0 {
		b.Config = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Config[k] = v
	}
	return b
}
