/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	meta "github.com/nagare-media/engine/pkg/apis/meta"
	batchv1 "k8s.io/api/batch/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TaskSpecApplyConfiguration represents a declarative configuration of the TaskSpec type for use
// with apply.
//
// Specification of a Task.
type TaskSpecApplyConfiguration struct {
	// Reference to a TaskTemplate or ClusterTaskTemplate. Only references to these two kinds are allowed. A Task can only
	// reference TaskTemplates from its own Namespace.
	TaskTemplateRef *meta.LocalObjectReference `json:"taskTemplateRef,omitempty"`
	// Human readable description of this Task.
	HumanReadable *HumanReadableTaskDescriptionApplyConfiguration `json:"humanReadable,omitempty"`
	// Reference to a MediaProcessingEntity or ClusterMediaProcessingEntity. Only references to these two kinds are
	// allowed. A Task can only reference MediaProcessingEntities from its own Namespace. This field is required if no
	// mediaProcessingEntitySelector is specified. If both are specified, mediaProcessingEntityRef has precedence. Both
	// fields may be omitted if a TaskTemplate is used that specifies a MediaProcessingEntity.
	MediaProcessingEntityRef *meta.LocalObjectReference `json:"mediaProcessingEntityRef,omitempty"`
	// Label selector for a MediaProcessingEntity or ClusterMediaProcessingEntity. MediaProcessingEntity has precedence
	// over ClusterMediaProcessingEntity. If multiple Media Processing Entities are selected, the newest one is chosen.
	// This field is required if no mediaProcessingEntityRef is specified. If both are specified, mediaProcessingEntityRef
	// has precedence. Both fields may be omitted if a TaskTemplate is used that specifies a MediaProcessingEntity.
	MediaProcessingEntitySelector *v1.LabelSelectorApplyConfiguration `json:"mediaProcessingEntitySelector,omitempty"`
	// Reference to a Workflow. Only references to Workflow are allowed. A Task can only reference Workflow from its own
	// Namespace.
	WorkflowRef *meta.LocalObjectReference `json:"workflowRef,omitempty"`
	// Reference to a Function or ClusterFunction. Only references to these two kinds are allowed. A Task can only
	// reference Functions from its own Namespace. This field is required if no FunctionSelector is specified. If both are
	// specified, FunctionRef has precedence. Both fields may be omitted if a TaskTemplate is used that specifies a
	// Function.
	FunctionRef *meta.LocalObjectReference `json:"functionRef,omitempty"`
	// Label selector for a Function or ClusterFunction. Function has precedence over ClusterFunction. If multiple
	// Functions are selected, the Function with the newest version is chosen. This field is required if no FunctionRef is
	// specified. If both are specified, FunctionRef has precedence. Both fields may be omitted if a TaskTemplate is used
	// that specifies a Function.
	FunctionSelector *v1.LabelSelectorApplyConfiguration `json:"functionSelector,omitempty"`
	// Patches applied to the Job template description of the Function.
	//
	// Only these fields may be patched:
	// TODO: update white list
	// TODO: enforce limits
	// TODO: which fields should be patchable?
	TemplatePatches *batchv1.JobTemplateSpec `json:"templatePatches,omitempty"`
	// Policy for dealing with a failed Job resulting from this Task. Conditions for when a Job is considered as failure
	// are defined in the templates `jobFailurePolicy` field.
	JobFailurePolicy *JobFailurePolicyApplyConfiguration `json:"jobFailurePolicy,omitempty"`
	// Input ports of this task.
	InputPorts []InputPortBindingApplyConfiguration `json:"inputPorts,omitempty"`
	// Output ports of this task.
	OutputPorts []OutputPortBindingApplyConfiguration `json:"outputPorts,omitempty"`
	// Configuration values.
	Config map[string]string `json:"config,omitempty"`
}

// TaskSpecApplyConfiguration constructs a declarative configuration of the TaskSpec type for use with
// apply.
func TaskSpec() *TaskSpecApplyConfiguration {
	return &TaskSpecApplyConfiguration{}
}

// WithTaskTemplateRef sets the TaskTemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TaskTemplateRef field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithTaskTemplateRef(value meta.LocalObjectReference) *TaskSpecApplyConfiguration {
	b.TaskTemplateRef = &value
	return b
}

// WithHumanReadable sets the HumanReadable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HumanReadable field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithHumanReadable(value *HumanReadableTaskDescriptionApplyConfiguration) *TaskSpecApplyConfiguration {
	b.HumanReadable = value
	return b
}

// WithMediaProcessingEntityRef sets the MediaProcessingEntityRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MediaProcessingEntityRef field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithMediaProcessingEntityRef(value meta.LocalObjectReference) *TaskSpecApplyConfiguration {
	b.MediaProcessingEntityRef = &value
	return b
}

// WithMediaProcessingEntitySelector sets the MediaProcessingEntitySelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MediaProcessingEntitySelector field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithMediaProcessingEntitySelector(value *v1.LabelSelectorApplyConfiguration) *TaskSpecApplyConfiguration {
	b.MediaProcessingEntitySelector = value
	return b
}

// WithWorkflowRef sets the WorkflowRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkflowRef field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithWorkflowRef(value meta.LocalObjectReference) *TaskSpecApplyConfiguration {
	b.WorkflowRef = &value
	return b
}

// WithFunctionRef sets the FunctionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FunctionRef field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithFunctionRef(value meta.LocalObjectReference) *TaskSpecApplyConfiguration {
	b.FunctionRef = &value
	return b
}

// WithFunctionSelector sets the FunctionSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FunctionSelector field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithFunctionSelector(value *v1.LabelSelectorApplyConfiguration) *TaskSpecApplyConfiguration {
	b.FunctionSelector = value
	return b
}

// WithTemplatePatches sets the TemplatePatches field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplatePatches field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithTemplatePatches(value batchv1.JobTemplateSpec) *TaskSpecApplyConfiguration {
	b.TemplatePatches = &value
	return b
}

// WithJobFailurePolicy sets the JobFailurePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobFailurePolicy field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithJobFailurePolicy(value *JobFailurePolicyApplyConfiguration) *TaskSpecApplyConfiguration {
	b.JobFailurePolicy = value
	return b
}

// WithInputPorts adds the given value to the InputPorts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InputPorts field.
func (b *TaskSpecApplyConfiguration) WithInputPorts(values ...*InputPortBindingApplyConfiguration) *TaskSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithInputPorts")
		}
		b.InputPorts = append(b.InputPorts, *values[i])
	}
	return b
}

// WithOutputPorts adds the given value to the OutputPorts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OutputPorts field.
func (b *TaskSpecApplyConfiguration) WithOutputPorts(values ...*OutputPortBindingApplyConfiguration) *TaskSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOutputPorts")
		}
		b.OutputPorts = append(b.OutputPorts, *values[i])
	}
	return b
}

// WithConfig puts the entries into the Config field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Config field,
// overwriting an existing map entries in Config field with the same key.
func (b *TaskSpecApplyConfiguration) WithConfig(entries map[string]string) *TaskSpecApplyConfiguration {
	if b.Config == nil && len(entries) > 0 {
		b.Config = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Config[k] = v
	}
	return b
}
