/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nagare-media/engine/api/v1alpha1"
)

// VideoMediaStreamApplyConfiguration represents a declarative configuration of the VideoMediaStream type for use
// with apply.
type VideoMediaStreamApplyConfiguration struct {
	BitDepth   *byte                              `json:"bitDepth,omitempty"`
	Resolution *VideoResolutionApplyConfiguration `json:"resolution,omitempty"`
	FrameRate  *FrameRateApplyConfiguration       `json:"frameRate,omitempty"`
	FieldOrder *apiv1alpha1.FieldOrder            `json:"fieldOrder,omitempty"`
	Color      *VideoColorApplyConfiguration      `json:"color,omitempty"`
}

// VideoMediaStreamApplyConfiguration constructs a declarative configuration of the VideoMediaStream type for use with
// apply.
func VideoMediaStream() *VideoMediaStreamApplyConfiguration {
	return &VideoMediaStreamApplyConfiguration{}
}

// WithBitDepth sets the BitDepth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BitDepth field is set to the value of the last call.
func (b *VideoMediaStreamApplyConfiguration) WithBitDepth(value byte) *VideoMediaStreamApplyConfiguration {
	b.BitDepth = &value
	return b
}

// WithResolution sets the Resolution field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resolution field is set to the value of the last call.
func (b *VideoMediaStreamApplyConfiguration) WithResolution(value *VideoResolutionApplyConfiguration) *VideoMediaStreamApplyConfiguration {
	b.Resolution = value
	return b
}

// WithFrameRate sets the FrameRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FrameRate field is set to the value of the last call.
func (b *VideoMediaStreamApplyConfiguration) WithFrameRate(value *FrameRateApplyConfiguration) *VideoMediaStreamApplyConfiguration {
	b.FrameRate = value
	return b
}

// WithFieldOrder sets the FieldOrder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldOrder field is set to the value of the last call.
func (b *VideoMediaStreamApplyConfiguration) WithFieldOrder(value apiv1alpha1.FieldOrder) *VideoMediaStreamApplyConfiguration {
	b.FieldOrder = &value
	return b
}

// WithColor sets the Color field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Color field is set to the value of the last call.
func (b *VideoMediaStreamApplyConfiguration) WithColor(value *VideoColorApplyConfiguration) *VideoMediaStreamApplyConfiguration {
	b.Color = value
	return b
}
