/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// VideoResolutionApplyConfiguration represents a declarative configuration of the VideoResolution type for use
// with apply.
type VideoResolutionApplyConfiguration struct {
	Width *int32  `json:"width,omitempty"`
	Hight *int32  `json:"hight,omitempty"`
	SAR   *string `json:"sar,omitempty"`
}

// VideoResolutionApplyConfiguration constructs a declarative configuration of the VideoResolution type for use with
// apply.
func VideoResolution() *VideoResolutionApplyConfiguration {
	return &VideoResolutionApplyConfiguration{}
}

// WithWidth sets the Width field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Width field is set to the value of the last call.
func (b *VideoResolutionApplyConfiguration) WithWidth(value int32) *VideoResolutionApplyConfiguration {
	b.Width = &value
	return b
}

// WithHight sets the Hight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hight field is set to the value of the last call.
func (b *VideoResolutionApplyConfiguration) WithHight(value int32) *VideoResolutionApplyConfiguration {
	b.Hight = &value
	return b
}

// WithSAR sets the SAR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SAR field is set to the value of the last call.
func (b *VideoResolutionApplyConfiguration) WithSAR(value string) *VideoResolutionApplyConfiguration {
	b.SAR = &value
	return b
}
