/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nagare-media/engine/api/v1alpha1"
)

// VideoColorApplyConfiguration represents a declarative configuration of the VideoColor type for use
// with apply.
type VideoColorApplyConfiguration struct {
	Model             *string                        `json:"model,omitempty"`
	ChromaSubsampling *apiv1alpha1.ChromaSubsampling `json:"chromaSubsampling,omitempty"`
	Range             *apiv1alpha1.ColorRange        `json:"range,omitempty"`
	Space             *string                        `json:"space,omitempty"`
	Primaries         *string                        `json:"primaries,omitempty"`
	Transfer          *string                        `json:"transfer,omitempty"`
}

// VideoColorApplyConfiguration constructs a declarative configuration of the VideoColor type for use with
// apply.
func VideoColor() *VideoColorApplyConfiguration {
	return &VideoColorApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *VideoColorApplyConfiguration) WithModel(value string) *VideoColorApplyConfiguration {
	b.Model = &value
	return b
}

// WithChromaSubsampling sets the ChromaSubsampling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChromaSubsampling field is set to the value of the last call.
func (b *VideoColorApplyConfiguration) WithChromaSubsampling(value apiv1alpha1.ChromaSubsampling) *VideoColorApplyConfiguration {
	b.ChromaSubsampling = &value
	return b
}

// WithRange sets the Range field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Range field is set to the value of the last call.
func (b *VideoColorApplyConfiguration) WithRange(value apiv1alpha1.ColorRange) *VideoColorApplyConfiguration {
	b.Range = &value
	return b
}

// WithSpace sets the Space field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Space field is set to the value of the last call.
func (b *VideoColorApplyConfiguration) WithSpace(value string) *VideoColorApplyConfiguration {
	b.Space = &value
	return b
}

// WithPrimaries sets the Primaries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Primaries field is set to the value of the last call.
func (b *VideoColorApplyConfiguration) WithPrimaries(value string) *VideoColorApplyConfiguration {
	b.Primaries = &value
	return b
}

// WithTransfer sets the Transfer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transfer field is set to the value of the last call.
func (b *VideoColorApplyConfiguration) WithTransfer(value string) *VideoColorApplyConfiguration {
	b.Transfer = &value
	return b
}
