/*
Copyright 2022-2025 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nagare-media/engine/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WorkflowStatusApplyConfiguration represents a declarative configuration of the WorkflowStatus type for use
// with apply.
//
// Status of a Workflow.
type WorkflowStatusApplyConfiguration struct {
	// The status of this Workflow.
	Phase *apiv1alpha1.WorkflowPhase `json:"phase,omitempty"`
	// The latest available observations of an object's current state. When a Workflow fails, one of the conditions will
	// have type "Failed" and status true. When a Workflow is completed, one of the conditions will have type "Complete"
	// and status true.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
	// A human readable message indicating why the Workflow is in this condition.
	Message *string `json:"message,omitempty"`
	// Represents time when the Workflow controller first started processing a Workflow. It is represented in RFC3339 form
	// and is in UTC.
	QueuedTime *v1.Time `json:"queuedTime,omitempty"`
	// Represents time when the Workflow controller transitioned to the "running" phase. It is represented in RFC3339 form
	// and is in UTC.
	StartTime *v1.Time `json:"startTime,omitempty"`
	// Represents time when the Workflow has ended processing (either failed or completed). It is not guaranteed to be set
	// in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
	EndTime *v1.Time `json:"endTime,omitempty"`
	// The number of total Tasks.
	Total *int32 `json:"total,omitempty"`
	// The number of Tasks which reached phase "Initializing", "JobPending" or "Running".
	Active *int32 `json:"active,omitempty"`
	// The number of Tasks which reached phase "Succeeded".
	Succeeded *int32 `json:"succeeded,omitempty"`
	// The number of Tasks which reached phase "Failed".
	Failed *int32 `json:"failed,omitempty"`
}

// WorkflowStatusApplyConfiguration constructs a declarative configuration of the WorkflowStatus type for use with
// apply.
func WorkflowStatus() *WorkflowStatusApplyConfiguration {
	return &WorkflowStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithPhase(value apiv1alpha1.WorkflowPhase) *WorkflowStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *WorkflowStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *WorkflowStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithMessage(value string) *WorkflowStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithQueuedTime sets the QueuedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QueuedTime field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithQueuedTime(value v1.Time) *WorkflowStatusApplyConfiguration {
	b.QueuedTime = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithStartTime(value v1.Time) *WorkflowStatusApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithEndTime sets the EndTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndTime field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithEndTime(value v1.Time) *WorkflowStatusApplyConfiguration {
	b.EndTime = &value
	return b
}

// WithTotal sets the Total field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Total field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithTotal(value int32) *WorkflowStatusApplyConfiguration {
	b.Total = &value
	return b
}

// WithActive sets the Active field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Active field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithActive(value int32) *WorkflowStatusApplyConfiguration {
	b.Active = &value
	return b
}

// WithSucceeded sets the Succeeded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Succeeded field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithSucceeded(value int32) *WorkflowStatusApplyConfiguration {
	b.Succeeded = &value
	return b
}

// WithFailed sets the Failed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Failed field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithFailed(value int32) *WorkflowStatusApplyConfiguration {
	b.Failed = &value
	return b
}
