mode: standalone

DeploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 1

rootUser: root
rootPassword: rootroot

replicas: 1

persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 10Gi

ingress:
  enabled: true
  path: /
  hosts:
    - s3.localtest.me

consoleIngress:
  enabled: true
  hosts:
    - minio.localtest.me

resources:
  requests: ~

users:
  - accessKey: MLYEAE6AES7IUSL4APYL
    secretKey: snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H
    policy: consoleAdmin

buckets:
  - name: nagare-media-engine-tests
    policy: download
    purge: false
    versioning: false
    objectlocking: false
