apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-nbmp
  namespace: system
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
      - name: gateway-nbmp
        args:
        - "--config=gateway-nbmp_configuration.yaml"
        - "--zap-devel"
        - "--zap-stacktrace-level=error"
        - "--zap-log-level=2"
