apiVersion: engine.nagare.media/v1alpha1
kind: WorkflowManagerHelperData

workflow:
  id: b2e6a8be-7512-414c-afef-239c5b009a98
  humanReadable:
    name: test-recovery

task:
  id: a356af70-baed-488d-9fbd-77843221f5ef
  humanReadable:
    name: test-recovery
  inputs:
    - id: e4b47e85-f80b-426e-8d8d-32b5f834a2fc
      type: media
      direction: pull
      portBindings:
        - id: input
      url: http://minio.s3.svc.cluster.local.localtest.me:9000/nagare-media-engine-tests/inputs/caminandes-1-llama-drama.mp4
      metadata:
        streams:
          - duration: 1m30s
            video:
              frameRate:
                average: "24"
    - id: f080d031-99ea-4dbc-a297-4015ce13f26d
      type: metadata
      direction: push
      portBindings:
        - id: report
      url: http://localhost:8080/events
      metadata:
        mimeType: application/cloudevents+json
  outputs:
    - id: f6a65c06-716a-4d95-b777-58fac934015d
      type: media
      direction: push
      portBindings:
        - id: output
      url: s3://minio.s3.svc.cluster.local.localtest.me:9000/nagare-media-engine-tests/outputs/caminandes-1-llama-drama.txt?INSECURE=true&AWS_ACCESS_KEY_ID=MLYEAE6AES7IUSL4APYL&AWS_SECRET_ACCESS_KEY=snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H
      # -> http://minio.s3.svc.cluster.local.localtest.me:9000/nagare-media-engine-tests/outputs/caminandes-1-llama-drama.txt
  config:
    mmsys-test-scene-detection.engine.nagare.media/test: test-recovery
    mmsys-test-scene-detection.engine.nagare.media/max-number-of-simulated-crashes: "1"
    mmsys-test-scene-detection.engine.nagare.media/simulated-crash-wait-duration: 20s

system:
  nats:
    url: nats://nats.nats.svc.cluster.local.localtest.me:4222
