apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: nagare-media-engine
build:
  artifacts:
    - image: ghcr.io/nagare-media/engine/controller
      context: .
      docker:
        dockerfile: build/package/image/controller/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/gateway-nbmp
      context: .
      docker:
        dockerfile: build/package/image/gateway-nbmp/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
    concurrency: 0 # = no-limit
manifests:
  kustomize:
    paths:
      - config/skaffold
deploy:
  kubeContext: kind-nagare-media-mgmt
  kubectl:
    flags:
      apply:
        - --server-side
