apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: nagare-media-engine
build:
  artifacts:
    - image: ghcr.io/nagare-media/engine/function-noop
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-noop/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
      hooks:
        after:
          # Load image into kind clusters
          - os: ["linux", "darwin"]
            command: ["kind", "load", "docker-image", "--name", "nagare-media-mgmt", "$SKAFFOLD_IMAGE"]
          - os: ["linux", "darwin"]
            command: ["kind", "load", "docker-image", "--name", "nagare-media-edge", "$SKAFFOLD_IMAGE"]
    - image: ghcr.io/nagare-media/engine/gateway-nbmp
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/gateway-nbmp/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/workflow-manager
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/workflow-manager/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/workflow-manager-helper
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/workflow-manager-helper/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
      hooks:
        after:
          # Load image into kind clusters
          - os: ["linux", "darwin"]
            command: ["kind", "load", "docker-image", "--name", "nagare-media-mgmt", "$SKAFFOLD_IMAGE"]
          - os: ["linux", "darwin"]
            command: ["kind", "load", "docker-image", "--name", "nagare-media-edge", "$SKAFFOLD_IMAGE"]
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
    concurrency: 0 # = no-limit
manifests:
  kustomize:
    paths:
      - config/output-skaffold
deploy:
  kubeContext: kind-nagare-media-mgmt
  kubectl:
    flags:
      apply:
        - --server-side
