apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: nagare-media-engine
build:
  artifacts:
    - image: ghcr.io/nagare-media/engine/function-data-buffer-fs
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-data-buffer-fs/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-data-copy
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-data-copy/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-data-discard
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-data-discard/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-generic-noop
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-generic-noop/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-generic-sleep
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-generic-sleep/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-media-encode
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-media-encode/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-media-generate-testpattern
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-media-generate-testpattern/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-media-merge
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-media-merge/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-media-metadata-technical
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-media-metadata-technical/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-media-package-hls
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-media-package-hls/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/function-script-lua
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/function-script-lua/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/gateway-nbmp
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/gateway-nbmp/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/workflow-manager
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/workflow-manager/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
    - image: ghcr.io/nagare-media/engine/workflow-manager-helper
      runtimeType: go
      context: .
      docker:
        dockerfile: build/package/image/workflow-manager-helper/Dockerfile.generic.generic
        pullParent: false
        noCache: false
        squash: false
        buildArgs:
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          GOVERSION: "{{ .GOVERSION }}"
          BUILD_DATE: "{{ .BUILD_DATE }}"
          GIT_COMMIT: "{{ .GIT_COMMIT }}"
          GIT_TREE_STATE: "{{ .GIT_TREE_STATE }}"
          VERSION: "{{ .VERSION }}"
  tagPolicy:
    customTemplate:
      template: "dev"
  local:
    push: false
    useBuildkit: true
    concurrency: 0 # = no-limit
manifests:
  kustomize:
    paths:
      - config/output-skaffold
deploy:
  kubeContext: kind-nagare-media-mgmt
  kubectl:
    flags:
      apply:
        - --server-side
    hooks:
      before:
        # Load function image into kind clusters
        - host:
            os: ["linux", "darwin"]
            command:
              - "kind"
              - "load"
              - "docker-image"
              - "--name"
              - "nagare-media-mgmt"
              - "ghcr.io/nagare-media/engine/workflow-manager-helper:dev"
              - "ghcr.io/nagare-media/engine/function-data-buffer-fs:dev"
              - "ghcr.io/nagare-media/engine/function-generic-noop:dev"
              - "ghcr.io/nagare-media/engine/function-generic-sleep:dev"
              - "ghcr.io/nagare-media/engine/function-media-encode:dev"
              - "ghcr.io/nagare-media/engine/function-media-generate-testpattern:dev"
              - "ghcr.io/nagare-media/engine/function-media-merge:dev"
              - "ghcr.io/nagare-media/engine/function-media-metadata-technical:dev"
              - "ghcr.io/nagare-media/engine/function-media-package-hls:dev"
              - "ghcr.io/nagare-media/engine/function-script-lua:dev"
        - host:
            os: ["linux", "darwin"]
            command:
              - "kind"
              - "load"
              - "docker-image"
              - "--name"
              - "nagare-media-edge"
              - "ghcr.io/nagare-media/engine/workflow-manager-helper:dev"
              - "ghcr.io/nagare-media/engine/function-data-buffer-fs:dev"
              - "ghcr.io/nagare-media/engine/function-generic-noop:dev"
              - "ghcr.io/nagare-media/engine/function-generic-sleep:dev"
              - "ghcr.io/nagare-media/engine/function-media-encode:dev"
              - "ghcr.io/nagare-media/engine/function-media-generate-testpattern:dev"
              - "ghcr.io/nagare-media/engine/function-media-merge:dev"
              - "ghcr.io/nagare-media/engine/function-media-metadata-technical:dev"
              - "ghcr.io/nagare-media/engine/function-media-package-hls:dev"
              - "ghcr.io/nagare-media/engine/function-script-lua:dev"
      after:
        # add test resources
        - host:
            os: ["linux", "darwin"]
            command: ["kubectl", "--context", "kind-nagare-media-mgmt", "apply", "--server-side", "-f", "config/samples/k8s/v1alpha1_engine.nagare.media_functions_*.yaml"]
        - host:
            os: ["linux", "darwin"]
            command: ["kubectl", "--context", "kind-nagare-media-mgmt", "apply", "--server-side", "-f", "config/samples/k8s/v1alpha1_engine.nagare.media_mediaprocessingentities_*.yaml"]
