apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: gateway-nbmp
    app.kubernetes.io/component: gateway-nbmp
    app.kubernetes.io/created-by: nagare-media-engine
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/managed-by: kustomize
  name: gateway-nbmp
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: gateway-nbmp
      app.kubernetes.io/component: gateway-nbmp
      app.kubernetes.io/part-of: nagare-media-engine
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: gateway-nbmp
      labels:
        app.kubernetes.io/instance: gateway-nbmp
        app.kubernetes.io/component: gateway-nbmp
        app.kubernetes.io/part-of: nagare-media-engine
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: gateway-nbmp
      terminationGracePeriodSeconds: 10
      containers:
        - name: gateway-nbmp
          image: ghcr.io/nagare-media/engine/gateway-nbmp:dev
          command:
            - /gateway-nbmp
          args:
            - "--config=/config/gateway-nbmp.yaml"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO: define default resource allocations
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - name: gateway-nbmp-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: gateway-nbmp-config
          secret:
            name: gateway-nbmp-config
            defaultMode: 420
