resources:
  - gateway-nbmp.yaml
  - gateway-nbmp_service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: gateway-nbmp-config
    files:
      - gateway-nbmp.yaml=gateway-nbmp_config.yaml
