volumes:
  s3: {}
  nats: {}

services:
  nats:
    image: nats:2-alpine
    command: --http_port 8222 --jetstream --store_dir /data
    ports:
      - 8222:8222
      - 4222:4222
    volumes:
      - nats:/data

  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    command: minio server /data --console-address ":8091"
    environment:
      MINIO_ROOT_USER: MLYEAE6AES7IUSL4APYL
      MINIO_ROOT_PASSWORD: snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H
      MINIO_REGION_NAME: us-east-1
    ports:
      - 9000:9000
    volumes:
      - s3:/data

  minio-populate-buckets:
    image: ghcr.io/nagare-media/ingest/mc-media-cache
    build:
      context: .
      dockerfile_inline: |
        FROM minio/mc:RELEASE.2024-08-17T11-33-50Z
        ADD https://public.s3.shio.services/media/testing/full-caminandes-1-llama-drama.mp4 /data/caminandes-1-llama-drama.mp4
    entrypoint: >
      /bin/sh -c '
        sleep 2;
        /usr/bin/mc config host add s3 http://minio:9000 MLYEAE6AES7IUSL4APYL snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H --api S3v4;
        /usr/bin/mc mb s3/nagare-media-engine-tests;
        /usr/bin/mc anonymous set download s3/nagare-media-engine-tests;
        /usr/bin/mc cp /data/caminandes-1-llama-drama.mp4 s3/nagare-media-engine-tests/inputs/caminandes-1-llama-drama.mp4;
        exit 0;
      '
