apiVersion: engine.nagare.media/v1alpha1
kind: GatewayNBMPConfiguration
metadata:
  labels:
    app.kubernetes.io/name: gatewaynbmpconfiguration
    app.kubernetes.io/instance: gateway-nbmp-configuration
    app.kubernetes.io/component: gateway-nbmp
    app.kubernetes.io/created-by: nagare-media-engine
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/managed-by: kustomize
webserver:
  bindAddress: :8080
