apiVersion: v1
kind: Service
metadata:
  name: gateway-nbmp
  namespace: system
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: gateway-nbmp
    app.kubernetes.io/component: gateway-nbmp
    app.kubernetes.io/created-by: nagare-media-engine
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: gateway-nbmp
    app.kubernetes.io/component: gateway-nbmp
  ports:
  - name: http
    port: 8080
    targetPort: http
