resources:
- gateway-nbmp.yaml
- gateway-nbmp_service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: gateway-nbmp-config
  files:
  - gateway-nbmp_configuration.yaml
