# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustermedialocations.engine.nagare.media
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: system
          name: workflow-manager
          path: /convert
          port: 9443
      conversionReviewVersions:
        - v1
