apiVersion: engine.nagare.media/v1alpha1
kind: Workflow
metadata:
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/instance: workflow-sample
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nagare-media-engine
  name: workflow-sample
spec:
  # TODO(user): Add fields here
