apiVersion: engine.nagare.media/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: task
    app.kubernetes.io/instance: task-sample
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nagare-media-engine
  name: task-sample
spec:
  # TODO(user): Add fields here
