apiVersion: engine.nagare.media/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: function
    app.kubernetes.io/instance: function-sample
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nagare-media-engine
  name: function-sample
spec:
  # TODO(user): Add fields here
