//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022-2023 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/nagare-media/engine/pkg/apis/meta"
	batchv1 "k8s.io/api/batch/v1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	timex "time"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSAuth) DeepCopyInto(out *AWSAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSAuth.
func (in *AWSAuth) DeepCopy() *AWSAuth {
	if in == nil {
		return nil
	}
	out := new(AWSAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFunction) DeepCopyInto(out *ClusterFunction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFunction.
func (in *ClusterFunction) DeepCopy() *ClusterFunction {
	if in == nil {
		return nil
	}
	out := new(ClusterFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterFunction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFunctionList) DeepCopyInto(out *ClusterFunctionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterFunction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFunctionList.
func (in *ClusterFunctionList) DeepCopy() *ClusterFunctionList {
	if in == nil {
		return nil
	}
	out := new(ClusterFunctionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterFunctionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMediaLocation) DeepCopyInto(out *ClusterMediaLocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMediaLocation.
func (in *ClusterMediaLocation) DeepCopy() *ClusterMediaLocation {
	if in == nil {
		return nil
	}
	out := new(ClusterMediaLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMediaLocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMediaLocationList) DeepCopyInto(out *ClusterMediaLocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterMediaLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMediaLocationList.
func (in *ClusterMediaLocationList) DeepCopy() *ClusterMediaLocationList {
	if in == nil {
		return nil
	}
	out := new(ClusterMediaLocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMediaLocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMediaProcessingEntity) DeepCopyInto(out *ClusterMediaProcessingEntity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMediaProcessingEntity.
func (in *ClusterMediaProcessingEntity) DeepCopy() *ClusterMediaProcessingEntity {
	if in == nil {
		return nil
	}
	out := new(ClusterMediaProcessingEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMediaProcessingEntity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMediaProcessingEntityList) DeepCopyInto(out *ClusterMediaProcessingEntityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterMediaProcessingEntity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMediaProcessingEntityList.
func (in *ClusterMediaProcessingEntityList) DeepCopy() *ClusterMediaProcessingEntityList {
	if in == nil {
		return nil
	}
	out := new(ClusterMediaProcessingEntityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMediaProcessingEntityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTaskTemplate) DeepCopyInto(out *ClusterTaskTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTaskTemplate.
func (in *ClusterTaskTemplate) DeepCopy() *ClusterTaskTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterTaskTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTaskTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTaskTemplateList) DeepCopyInto(out *ClusterTaskTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTaskTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTaskTemplateList.
func (in *ClusterTaskTemplateList) DeepCopy() *ClusterTaskTemplateList {
	if in == nil {
		return nil
	}
	out := new(ClusterTaskTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTaskTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerManagerConfiguration) DeepCopyInto(out *ControllerManagerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ControllerManagerConfigurationSpec.DeepCopyInto(&out.ControllerManagerConfigurationSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerManagerConfiguration.
func (in *ControllerManagerConfiguration) DeepCopy() *ControllerManagerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControllerManagerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerManagerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Function) DeepCopyInto(out *Function) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Function.
func (in *Function) DeepCopy() *Function {
	if in == nil {
		return nil
	}
	out := new(Function)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Function) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionList) DeepCopyInto(out *FunctionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Function, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionList.
func (in *FunctionList) DeepCopy() *FunctionList {
	if in == nil {
		return nil
	}
	out := new(FunctionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionSpec) DeepCopyInto(out *FunctionSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.DefaultConfig != nil {
		in, out := &in.DefaultConfig, &out.DefaultConfig
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionSpec.
func (in *FunctionSpec) DeepCopy() *FunctionSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNBMPConfiguration) DeepCopyInto(out *GatewayNBMPConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.GatewayNBMPConfigurationSpec.DeepCopyInto(&out.GatewayNBMPConfigurationSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNBMPConfiguration.
func (in *GatewayNBMPConfiguration) DeepCopy() *GatewayNBMPConfiguration {
	if in == nil {
		return nil
	}
	out := new(GatewayNBMPConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayNBMPConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNBMPConfigurationSpec) DeepCopyInto(out *GatewayNBMPConfigurationSpec) {
	*out = *in
	in.Webserver.DeepCopyInto(&out.Webserver)
	out.Services = in.Services
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNBMPConfigurationSpec.
func (in *GatewayNBMPConfigurationSpec) DeepCopy() *GatewayNBMPConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayNBMPConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAuthConfig) DeepCopyInto(out *HTTPAuthConfig) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(HTTPBasicAuth)
		**out = **in
	}
	if in.Digest != nil {
		in, out := &in.Digest, &out.Digest
		*out = new(HTTPDigestAuth)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(HTTPToken)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAuthConfig.
func (in *HTTPAuthConfig) DeepCopy() *HTTPAuthConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPBasicAuth) DeepCopyInto(out *HTTPBasicAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPBasicAuth.
func (in *HTTPBasicAuth) DeepCopy() *HTTPBasicAuth {
	if in == nil {
		return nil
	}
	out := new(HTTPBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPDigestAuth) DeepCopyInto(out *HTTPDigestAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPDigestAuth.
func (in *HTTPDigestAuth) DeepCopy() *HTTPDigestAuth {
	if in == nil {
		return nil
	}
	out := new(HTTPDigestAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPMediaLocation) DeepCopyInto(out *HTTPMediaLocation) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]Header, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueryArgs != nil {
		in, out := &in.QueryArgs, &out.QueryArgs
		*out = make([]QueryArg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(HTTPAuthConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPMediaLocation.
func (in *HTTPMediaLocation) DeepCopy() *HTTPMediaLocation {
	if in == nil {
		return nil
	}
	out := new(HTTPMediaLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPToken) DeepCopyInto(out *HTTPToken) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.HeaderName != nil {
		in, out := &in.HeaderName, &out.HeaderName
		*out = new(string)
		**out = **in
	}
	if in.HeaderValuePrefix != nil {
		in, out := &in.HeaderValuePrefix, &out.HeaderValuePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPToken.
func (in *HTTPToken) DeepCopy() *HTTPToken {
	if in == nil {
		return nil
	}
	out := new(HTTPToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Header) DeepCopyInto(out *Header) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(meta.ConfigMapOrSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Header.
func (in *Header) DeepCopy() *Header {
	if in == nil {
		return nil
	}
	out := new(Header)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanReadableTaskDescription) DeepCopyInto(out *HumanReadableTaskDescription) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanReadableTaskDescription.
func (in *HumanReadableTaskDescription) DeepCopy() *HumanReadableTaskDescription {
	if in == nil {
		return nil
	}
	out := new(HumanReadableTaskDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanReadableWorkflowDescription) DeepCopyInto(out *HumanReadableWorkflowDescription) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanReadableWorkflowDescription.
func (in *HumanReadableWorkflowDescription) DeepCopy() *HumanReadableWorkflowDescription {
	if in == nil {
		return nil
	}
	out := new(HumanReadableWorkflowDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobFailurePolicy) DeepCopyInto(out *JobFailurePolicy) {
	*out = *in
	if in.DefaultAction != nil {
		in, out := &in.DefaultAction, &out.DefaultAction
		*out = new(JobFailurePolicyAction)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobFailurePolicy.
func (in *JobFailurePolicy) DeepCopy() *JobFailurePolicy {
	if in == nil {
		return nil
	}
	out := new(JobFailurePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubeconfig) DeepCopyInto(out *Kubeconfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubeconfig.
func (in *Kubeconfig) DeepCopy() *Kubeconfig {
	if in == nil {
		return nil
	}
	out := new(Kubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalMediaProcessingEntity) DeepCopyInto(out *LocalMediaProcessingEntity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalMediaProcessingEntity.
func (in *LocalMediaProcessingEntity) DeepCopy() *LocalMediaProcessingEntity {
	if in == nil {
		return nil
	}
	out := new(LocalMediaProcessingEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaLocation) DeepCopyInto(out *MediaLocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaLocation.
func (in *MediaLocation) DeepCopy() *MediaLocation {
	if in == nil {
		return nil
	}
	out := new(MediaLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MediaLocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaLocationConfig) DeepCopyInto(out *MediaLocationConfig) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPMediaLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3MediaLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.Opencast != nil {
		in, out := &in.Opencast, &out.Opencast
		*out = new(OpencastMediaLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.RTMP != nil {
		in, out := &in.RTMP, &out.RTMP
		*out = new(RTMPMediaLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.RTSP != nil {
		in, out := &in.RTSP, &out.RTSP
		*out = new(RTSPMediaLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.RIST != nil {
		in, out := &in.RIST, &out.RIST
		*out = new(RISTMediaLocation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaLocationConfig.
func (in *MediaLocationConfig) DeepCopy() *MediaLocationConfig {
	if in == nil {
		return nil
	}
	out := new(MediaLocationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaLocationList) DeepCopyInto(out *MediaLocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MediaLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaLocationList.
func (in *MediaLocationList) DeepCopy() *MediaLocationList {
	if in == nil {
		return nil
	}
	out := new(MediaLocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MediaLocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaLocationSpec) DeepCopyInto(out *MediaLocationSpec) {
	*out = *in
	in.MediaLocationConfig.DeepCopyInto(&out.MediaLocationConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaLocationSpec.
func (in *MediaLocationSpec) DeepCopy() *MediaLocationSpec {
	if in == nil {
		return nil
	}
	out := new(MediaLocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaProcessingEntity) DeepCopyInto(out *MediaProcessingEntity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaProcessingEntity.
func (in *MediaProcessingEntity) DeepCopy() *MediaProcessingEntity {
	if in == nil {
		return nil
	}
	out := new(MediaProcessingEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MediaProcessingEntity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaProcessingEntityCondition) DeepCopyInto(out *MediaProcessingEntityCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaProcessingEntityCondition.
func (in *MediaProcessingEntityCondition) DeepCopy() *MediaProcessingEntityCondition {
	if in == nil {
		return nil
	}
	out := new(MediaProcessingEntityCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaProcessingEntityConfig) DeepCopyInto(out *MediaProcessingEntityConfig) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalMediaProcessingEntity)
		**out = **in
	}
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(RemoteMediaProcessingEntity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaProcessingEntityConfig.
func (in *MediaProcessingEntityConfig) DeepCopy() *MediaProcessingEntityConfig {
	if in == nil {
		return nil
	}
	out := new(MediaProcessingEntityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaProcessingEntityList) DeepCopyInto(out *MediaProcessingEntityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MediaProcessingEntity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaProcessingEntityList.
func (in *MediaProcessingEntityList) DeepCopy() *MediaProcessingEntityList {
	if in == nil {
		return nil
	}
	out := new(MediaProcessingEntityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MediaProcessingEntityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaProcessingEntitySpec) DeepCopyInto(out *MediaProcessingEntitySpec) {
	*out = *in
	in.MediaProcessingEntityConfig.DeepCopyInto(&out.MediaProcessingEntityConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaProcessingEntitySpec.
func (in *MediaProcessingEntitySpec) DeepCopy() *MediaProcessingEntitySpec {
	if in == nil {
		return nil
	}
	out := new(MediaProcessingEntitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaProcessingEntityStatus) DeepCopyInto(out *MediaProcessingEntityStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MediaProcessingEntityCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaProcessingEntityStatus.
func (in *MediaProcessingEntityStatus) DeepCopy() *MediaProcessingEntityStatus {
	if in == nil {
		return nil
	}
	out := new(MediaProcessingEntityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedMediaLocationReference) DeepCopyInto(out *NamedMediaLocationReference) {
	*out = *in
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedMediaLocationReference.
func (in *NamedMediaLocationReference) DeepCopy() *NamedMediaLocationReference {
	if in == nil {
		return nil
	}
	out := new(NamedMediaLocationReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpencastAuthConfig) DeepCopyInto(out *OpencastAuthConfig) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(HTTPBasicAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpencastAuthConfig.
func (in *OpencastAuthConfig) DeepCopy() *OpencastAuthConfig {
	if in == nil {
		return nil
	}
	out := new(OpencastAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpencastEndpointOverwrites) DeepCopyInto(out *OpencastEndpointOverwrites) {
	*out = *in
	if in.ExternalAPI != nil {
		in, out := &in.ExternalAPI, &out.ExternalAPI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpencastEndpointOverwrites.
func (in *OpencastEndpointOverwrites) DeepCopy() *OpencastEndpointOverwrites {
	if in == nil {
		return nil
	}
	out := new(OpencastEndpointOverwrites)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpencastMediaLocation) DeepCopyInto(out *OpencastMediaLocation) {
	*out = *in
	if in.EndpointOverwrites != nil {
		in, out := &in.EndpointOverwrites, &out.EndpointOverwrites
		*out = new(OpencastEndpointOverwrites)
		(*in).DeepCopyInto(*out)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]Header, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueryArgs != nil {
		in, out := &in.QueryArgs, &out.QueryArgs
		*out = make([]QueryArg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpencastMediaLocation.
func (in *OpencastMediaLocation) DeepCopy() *OpencastMediaLocation {
	if in == nil {
		return nil
	}
	out := new(OpencastMediaLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryArg) DeepCopyInto(out *QueryArg) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(meta.ConfigMapOrSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryArg.
func (in *QueryArg) DeepCopy() *QueryArg {
	if in == nil {
		return nil
	}
	out := new(QueryArg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RISTEncryption) DeepCopyInto(out *RISTEncryption) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RISTEncryption.
func (in *RISTEncryption) DeepCopy() *RISTEncryption {
	if in == nil {
		return nil
	}
	out := new(RISTEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RISTMediaLocation) DeepCopyInto(out *RISTMediaLocation) {
	*out = *in
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(string)
		**out = **in
	}
	if in.BufferSize != nil {
		in, out := &in.BufferSize, &out.BufferSize
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(RISTEncryption)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RISTMediaLocation.
func (in *RISTMediaLocation) DeepCopy() *RISTMediaLocation {
	if in == nil {
		return nil
	}
	out := new(RISTMediaLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RTMPAuthConfig) DeepCopyInto(out *RTMPAuthConfig) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(RTMPBasicAuth)
		**out = **in
	}
	if in.StreamingKey != nil {
		in, out := &in.StreamingKey, &out.StreamingKey
		*out = new(RTMPStreamingKeyAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RTMPAuthConfig.
func (in *RTMPAuthConfig) DeepCopy() *RTMPAuthConfig {
	if in == nil {
		return nil
	}
	out := new(RTMPAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RTMPBasicAuth) DeepCopyInto(out *RTMPBasicAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RTMPBasicAuth.
func (in *RTMPBasicAuth) DeepCopy() *RTMPBasicAuth {
	if in == nil {
		return nil
	}
	out := new(RTMPBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RTMPMediaLocation) DeepCopyInto(out *RTMPMediaLocation) {
	*out = *in
	if in.App != nil {
		in, out := &in.App, &out.App
		*out = new(string)
		**out = **in
	}
	if in.QueryArgs != nil {
		in, out := &in.QueryArgs, &out.QueryArgs
		*out = make([]QueryArg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RTMPMediaLocation.
func (in *RTMPMediaLocation) DeepCopy() *RTMPMediaLocation {
	if in == nil {
		return nil
	}
	out := new(RTMPMediaLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RTMPStreamingKeyAuth) DeepCopyInto(out *RTMPStreamingKeyAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RTMPStreamingKeyAuth.
func (in *RTMPStreamingKeyAuth) DeepCopy() *RTMPStreamingKeyAuth {
	if in == nil {
		return nil
	}
	out := new(RTMPStreamingKeyAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RTSPAuthConfig) DeepCopyInto(out *RTSPAuthConfig) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(RTSPBasicAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RTSPAuthConfig.
func (in *RTSPAuthConfig) DeepCopy() *RTSPAuthConfig {
	if in == nil {
		return nil
	}
	out := new(RTSPAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RTSPBasicAuth) DeepCopyInto(out *RTSPBasicAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RTSPBasicAuth.
func (in *RTSPBasicAuth) DeepCopy() *RTSPBasicAuth {
	if in == nil {
		return nil
	}
	out := new(RTSPBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RTSPMediaLocation) DeepCopyInto(out *RTSPMediaLocation) {
	*out = *in
	if in.TransportProtocol != nil {
		in, out := &in.TransportProtocol, &out.TransportProtocol
		*out = new(string)
		**out = **in
	}
	if in.QueryArgs != nil {
		in, out := &in.QueryArgs, &out.QueryArgs
		*out = make([]QueryArg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RTSPMediaLocation.
func (in *RTSPMediaLocation) DeepCopy() *RTSPMediaLocation {
	if in == nil {
		return nil
	}
	out := new(RTSPMediaLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteMediaProcessingEntity) DeepCopyInto(out *RemoteMediaProcessingEntity) {
	*out = *in
	out.Kubeconfig = in.Kubeconfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteMediaProcessingEntity.
func (in *RemoteMediaProcessingEntity) DeepCopy() *RemoteMediaProcessingEntity {
	if in == nil {
		return nil
	}
	out := new(RemoteMediaProcessingEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3AuthConfig) DeepCopyInto(out *S3AuthConfig) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3AuthConfig.
func (in *S3AuthConfig) DeepCopy() *S3AuthConfig {
	if in == nil {
		return nil
	}
	out := new(S3AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3MediaLocation) DeepCopyInto(out *S3MediaLocation) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3MediaLocation.
func (in *S3MediaLocation) DeepCopy() *S3MediaLocation {
	if in == nil {
		return nil
	}
	out := new(S3MediaLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicesConfiguration) DeepCopyInto(out *ServicesConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicesConfiguration.
func (in *ServicesConfiguration) DeepCopy() *ServicesConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServicesConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Task) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskCondition) DeepCopyInto(out *TaskCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskCondition.
func (in *TaskCondition) DeepCopy() *TaskCondition {
	if in == nil {
		return nil
	}
	out := new(TaskCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskList) DeepCopyInto(out *TaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskList.
func (in *TaskList) DeepCopy() *TaskList {
	if in == nil {
		return nil
	}
	out := new(TaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSpec) DeepCopyInto(out *TaskSpec) {
	*out = *in
	if in.TaskTemplateRef != nil {
		in, out := &in.TaskTemplateRef, &out.TaskTemplateRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
	if in.HumanReadable != nil {
		in, out := &in.HumanReadable, &out.HumanReadable
		*out = new(HumanReadableTaskDescription)
		(*in).DeepCopyInto(*out)
	}
	if in.MediaProcessingEntityRef != nil {
		in, out := &in.MediaProcessingEntityRef, &out.MediaProcessingEntityRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
	if in.MediaProcessingEntitySelector != nil {
		in, out := &in.MediaProcessingEntitySelector, &out.MediaProcessingEntitySelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.WorkflowRef = in.WorkflowRef
	if in.FunctionRef != nil {
		in, out := &in.FunctionRef, &out.FunctionRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
	if in.FunctionSelector != nil {
		in, out := &in.FunctionSelector, &out.FunctionSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TemplatePatches != nil {
		in, out := &in.TemplatePatches, &out.TemplatePatches
		*out = new(batchv1.JobTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.JobFailurePolicy != nil {
		in, out := &in.JobFailurePolicy, &out.JobFailurePolicy
		*out = new(JobFailurePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSpec.
func (in *TaskSpec) DeepCopy() *TaskSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskStatus) DeepCopyInto(out *TaskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TaskCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueuedTime != nil {
		in, out := &in.QueuedTime, &out.QueuedTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.MediaProcessingEntityRef != nil {
		in, out := &in.MediaProcessingEntityRef, &out.MediaProcessingEntityRef
		*out = new(meta.ObjectReference)
		**out = **in
	}
	if in.FunctionRef != nil {
		in, out := &in.FunctionRef, &out.FunctionRef
		*out = new(meta.ObjectReference)
		**out = **in
	}
	if in.JobRef != nil {
		in, out := &in.JobRef, &out.JobRef
		*out = new(meta.ExactObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskStatus.
func (in *TaskStatus) DeepCopy() *TaskStatus {
	if in == nil {
		return nil
	}
	out := new(TaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTemplate) DeepCopyInto(out *TaskTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTemplate.
func (in *TaskTemplate) DeepCopy() *TaskTemplate {
	if in == nil {
		return nil
	}
	out := new(TaskTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTemplateList) DeepCopyInto(out *TaskTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTemplateList.
func (in *TaskTemplateList) DeepCopy() *TaskTemplateList {
	if in == nil {
		return nil
	}
	out := new(TaskTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTemplateSpec) DeepCopyInto(out *TaskTemplateSpec) {
	*out = *in
	if in.HumanReadable != nil {
		in, out := &in.HumanReadable, &out.HumanReadable
		*out = new(HumanReadableTaskDescription)
		(*in).DeepCopyInto(*out)
	}
	if in.MediaProcessingEntityRef != nil {
		in, out := &in.MediaProcessingEntityRef, &out.MediaProcessingEntityRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
	if in.MediaProcessingEntitySelector != nil {
		in, out := &in.MediaProcessingEntitySelector, &out.MediaProcessingEntitySelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionRef != nil {
		in, out := &in.FunctionRef, &out.FunctionRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
	if in.FunctionSelector != nil {
		in, out := &in.FunctionSelector, &out.FunctionSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TemplatePatches != nil {
		in, out := &in.TemplatePatches, &out.TemplatePatches
		*out = new(batchv1.JobTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.JobFailurePolicy != nil {
		in, out := &in.JobFailurePolicy, &out.JobFailurePolicy
		*out = new(JobFailurePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTemplateSpec.
func (in *TaskTemplateSpec) DeepCopy() *TaskTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TaskTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebserverConfiguration) DeepCopyInto(out *WebserverConfiguration) {
	*out = *in
	if in.BindAddress != nil {
		in, out := &in.BindAddress, &out.BindAddress
		*out = new(string)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.WriteTimeout != nil {
		in, out := &in.WriteTimeout, &out.WriteTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.PublicBaseURL != nil {
		in, out := &in.PublicBaseURL, &out.PublicBaseURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebserverConfiguration.
func (in *WebserverConfiguration) DeepCopy() *WebserverConfiguration {
	if in == nil {
		return nil
	}
	out := new(WebserverConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workflow) DeepCopyInto(out *Workflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workflow.
func (in *Workflow) DeepCopy() *Workflow {
	if in == nil {
		return nil
	}
	out := new(Workflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Workflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowCondition) DeepCopyInto(out *WorkflowCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowCondition.
func (in *WorkflowCondition) DeepCopy() *WorkflowCondition {
	if in == nil {
		return nil
	}
	out := new(WorkflowCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowList) DeepCopyInto(out *WorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Workflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowList.
func (in *WorkflowList) DeepCopy() *WorkflowList {
	if in == nil {
		return nil
	}
	out := new(WorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowSpec) DeepCopyInto(out *WorkflowSpec) {
	*out = *in
	if in.HumanReadable != nil {
		in, out := &in.HumanReadable, &out.HumanReadable
		*out = new(HumanReadableWorkflowDescription)
		(*in).DeepCopyInto(*out)
	}
	if in.MediaLocations != nil {
		in, out := &in.MediaLocations, &out.MediaLocations
		*out = make([]NamedMediaLocationReference, len(*in))
		copy(*out, *in)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowSpec.
func (in *WorkflowSpec) DeepCopy() *WorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(WorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowStatus) DeepCopyInto(out *WorkflowStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WorkflowCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowStatus.
func (in *WorkflowStatus) DeepCopy() *WorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(WorkflowStatus)
	in.DeepCopyInto(out)
	return out
}
