apiVersion: engine.nagare.media/v1alpha1
kind: WorkflowManagerHelperData

workflow:
  id: 6d0b3b44-af0f-47f3-a1fe-548794c1cee4
  humanReadable:
    name: test-no-recovery
  config: ~

task:
  id: bdbfbb12-d14b-444e-8801-076b3ae162c6
  humanReadable:
    name: test-no-recovery
  inputs:
    - id: c206ab16-028f-410b-af09-cd12657f00e1
      type: media
      direction: pull
      portBindings:
        - id: input
      url: http://minio.s3.svc.cluster.local.localtest.me:9000/nagare-media-engine-tests/inputs/caminandes-1-llama-drama.mp4
      metadata:
        streams:
          - duration: 1m30s
            video:
              frameRate:
                average: "24"
    - id: 4c23a4c2-2554-42f7-b2a2-e4cdadcc68eb
      type: metadata
      direction: push
      portBindings:
        - id: report
      url: http://localhost:8080/events
      metadata:
        mimeType: application/cloudevents+json
  outputs:
    - id: 46ba0184-339c-4761-ab32-9219dfe27aab
      type: media
      direction: push
      portBindings:
        - id: output
      url: s3://minio.s3.svc.cluster.local.localtest.me:9000/nagare-media-engine-tests/outputs/caminandes-1-llama-drama.txt?INSECURE=true&AWS_ACCESS_KEY_ID=MLYEAE6AES7IUSL4APYL&AWS_SECRET_ACCESS_KEY=snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H
      # -> http://minio.s3.svc.cluster.local.localtest.me:9000/nagare-media-engine-tests/outputs/caminandes-1-llama-drama.txt
  config:
    mmsys-test-scene-detection.engine.nagare.media/test: test-no-recovery
    mmsys-test-scene-detection.engine.nagare.media/max-number-of-simulated-crashes: "1"
    mmsys-test-scene-detection.engine.nagare.media/simulated-crash-wait-duration: 20s

system:
  nats:
    url: nats://nats.nats.svc.cluster.local.localtest.me:4222
