apiVersion: engine.nagare.media/v1alpha1
kind: WorkflowManagerHelperData

workflow:
  id: 8c472ed0-2108-42d6-a2e4-b7476837a63a
  humanReadable:
    name: test-no-recovery-simple
  config: ~

task:
  id: ce2c6d2f-0371-4e9f-86f7-11f7b3c9ebe8
  humanReadable:
    name: test-no-recovery-simple
  inputs:
    - id: fb81676e-6d5a-418c-a7e2-42515467788a
      type: media
      direction: pull
      portBindings:
        - id: input
      url: http://localhost:9000/nagare-media-engine-tests/inputs/sintel.mov
      metadata:
        streams:
          - duration: 14m48s
            video:
              frameRate:
                average: 24
    - id: 18de69db-50d0-4dd9-bd34-4e33fdbe71df
      type: metadata
      direction: push
      portBindings:
        - id: report
      url: http://localhost:8080/events
      metadata:
        mimeType: application/cloudevents+json
  outputs:
    - id: 374f4dfb-a194-4b4a-89b2-1492dc41a66c
      type: media
      direction: push
      portBindings:
        - id: output
      url: s3://localhost:9000/nagare-media-engine-tests/outputs/sintel.mp4?INSECURE=true&AWS_ACCESS_KEY_ID=MLYEAE6AES7IUSL4APYL&AWS_SECRET_ACCESS_KEY=snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H
      # -> http://localhost:9000/nagare-media-engine-tests/outputs/sintel.mp4
  config:
    mmsys-test-encode.engine.nagare.media/test: test-no-recovery-simple
    mmsys-test-encode.engine.nagare.media/chunk-seconds: "60"
    mmsys-test-encode.engine.nagare.media/max-number-of-simulated-crashes: "2"
    mmsys-test-encode.engine.nagare.media/simulated-crash-wait-duration: 360s

system:
  nats:
    url: nats://localhost:4222
