apiVersion: engine.nagare.media/v1alpha1
kind: WorkflowManagerHelperData

workflow:
  id: 38280525-1831-4f4d-b38b-de7e5e58e35b
  humanReadable:
    name: baseline
  config: ~

task:
  id: c774949a-6785-4d60-9add-98af8b161cd8
  humanReadable:
    name: baseline
  inputs:
    - id: 0848ab75-2cee-4cfb-b94f-584cb4bd8313
      type: media
      direction: pull
      portBindings:
        - id: input
      url: http://minio.s3.svc.cluster.local.localtest.me:9000/nagare-media-engine-tests/inputs/caminandes-1-llama-drama.mp4
      metadata:
        streams:
          - duration: 1m30s
            video:
              frameRate:
                average: "24"
  outputs:
    - id: e482adcf-ca7a-46ff-a945-ccb7aae039f4
      type: media
      direction: push
      portBindings:
        - id: output
      url: s3://minio.s3.svc.cluster.local.localtest.me:9000/nagare-media-engine-tests/outputs/caminandes-1-llama-drama.txt?INSECURE=true&AWS_ACCESS_KEY_ID=MLYEAE6AES7IUSL4APYL&AWS_SECRET_ACCESS_KEY=snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H
      # -> http://minio.s3.svc.cluster.local.localtest.me:9000/nagare-media-engine-tests/outputs/caminandes-1-llama-drama.txt
  config:
    mmsys-test-scene-detection.engine.nagare.media/test: baseline

system:
  nats:
    url: nats://nats.nats.svc.cluster.local.localtest.me:4222
