apiVersion: engine.nagare.media/v1alpha1
kind: WorkflowManagerHelperData

workflow:
  id: 41f7a443-8fa5-4e08-9def-252826832f2c
  humanReadable:
    name: test-no-recovery-split-merge
  config: ~

task:
  id: fb747f6c-aa92-42b3-a112-e4674b3c67ce
  humanReadable:
    name: test-no-recovery-split-merge
  inputs:
    - id: 61ceb7bf-e703-4917-bd58-ce9aff2af460
      type: media
      direction: pull
      portBindings:
        - id: input
      url: http://minio.s3.svc.cluster.local:9000/nagare-media-engine-tests/inputs/sintel.mp4
      metadata:
        streams:
          - duration: 14m48s
            video:
              frameRate:
                average: 24
    - id: 5ed94853-107a-4826-9ba1-dd973bca962a
      type: metadata
      direction: push
      portBindings:
        - id: report
      url: http://localhost:8080/events
      metadata:
        mimeType: application/cloudevents+json
  outputs:
    - id: a06ecb9d-a66e-4589-91bb-6224dfd11d23
      type: media
      direction: push
      portBindings:
        - id: output
      url: s3://minio.s3.svc.cluster.local:9000/nagare-media-engine-tests/outputs/sintel.mp4?INSECURE=true&AWS_ACCESS_KEY_ID=MLYEAE6AES7IUSL4APYL&AWS_SECRET_ACCESS_KEY=snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H
      # -> http://minio.s3.svc.cluster.local:9000/nagare-media-engine-tests/outputs/sintel.mp4
  config:
    mmsys-test-encode.engine.nagare.media/test: test-no-recovery-split-merge
    mmsys-test-encode.engine.nagare.media/chunk-seconds: "60"
    mmsys-test-encode.engine.nagare.media/max-number-of-simulated-crashes: "2"
    mmsys-test-encode.engine.nagare.media/simulated-crash-wait-duration: 180s

system:
  nats:
    url: nats://nats.nats.svc.cluster.local:4222
