apiVersion: engine.nagare.media/v1alpha1
kind: WorkflowManagerHelperData

workflow:
  id: 459a108a-7eeb-40b2-b86c-9bd61ceddefd
  humanReadable:
    name: test-recovery-split-merge
  config: ~

task:
  id: 31353a5c-1c2e-4654-91ee-45b6d482b841
  humanReadable:
    name: test-recovery-split-merge
  inputs:
    - id: 94f90365-47e7-4681-89d6-790961ad4e72
      type: media
      direction: pull
      portBindings:
        - id: input
      url: http://localhost:9000/nagare-media-engine-tests/inputs/sintel.mov
      metadata:
        streams:
          - duration: 14m48s
            video:
              frameRate:
                average: 24
    - id: 96f6ae8e-b3ef-4391-b2ff-9662adb43904
      type: metadata
      direction: push
      portBindings:
        - id: report
      url: http://localhost:8080/events
      metadata:
        mimeType: application/cloudevents+json
  outputs:
    - id: 7e84e0f8-b83d-464d-809b-3d35fcd126ad
      type: media
      direction: push
      portBindings:
        - id: output
      url: s3://localhost:9000/nagare-media-engine-tests/outputs/sintel.mp4?INSECURE=true&AWS_ACCESS_KEY_ID=MLYEAE6AES7IUSL4APYL&AWS_SECRET_ACCESS_KEY=snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H
      # -> http://localhost:9000/nagare-media-engine-tests/outputs/sintel.mp4
  config:
    mmsys-test-encode.engine.nagare.media/test: test-recovery-split-merge
    mmsys-test-encode.engine.nagare.media/chunk-seconds: "60"

system:
  nats:
    url: nats://localhost:4222
