#!/bin/bash

# Copyright 2022-2024 The nagare media authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Validation

[ -n "${CONTROLLER_GEN}" ] || fatal "mandatory variable \$CONTROLLER_GEN is empty"
[ -n "${YQ}" ] || fatal "mandatory variable \$YQ is empty"

# Main

# CRDs
"${CONTROLLER_GEN}" \
  paths="./..." \
  crd \
  output:crd:artifacts:config=config/crd/bases

# webhooks
"${CONTROLLER_GEN}" \
  paths="./..." \
  webhook \
  output:stdout > config/deployment-workflow-manager/.workflow-manager_admission-webhooks.yaml

# set correct service name and port
"${YQ}" --no-colors '(.webhooks[].clientConfig.service.name = "workflow-manager") | (.webhooks[].clientConfig.service.port |= 9443)' \
  < config/deployment-workflow-manager/.workflow-manager_admission-webhooks.yaml \
  > config/deployment-workflow-manager/workflow-manager_admission-webhooks.yaml

rm config/deployment-workflow-manager/.workflow-manager_admission-webhooks.yaml

# RBAC
"${CONTROLLER_GEN}" \
  paths="./internal/workflow-manager/..." \
  rbac:roleName=workflow-manager \
  output:stdout > config/rbac/role-workflow-manager.yaml

"${CONTROLLER_GEN}" \
  paths="./internal/gateway-nbmp/..." \
  rbac:roleName=gateway-nbmp \
  output:stdout > config/rbac/role-gateway-nbmp.yaml
