#!/bin/bash

# Copyright 2022-2024 The nagare media authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Validation

[ -n "${ARCH}" ] || fatal "mandatory variable \$ARCH is empty"
[ -n "${VERSION}" ] || fatal "mandatory variable \$VERSION is empty"
[ -n "${GOVERSION}" ] || fatal "mandatory variable \$GOVERSION is empty"
[ -n "${ARGS}" ] || fatal "mandatory variable \$ARGS is empty"

# Variables

export OS="${OS:-linux}"
export ARCH="${ARCH}"
export VERSION="${VERSION}"
export GOVERSION="${GOVERSION}"
# fix build infos to make better use of caching
export BUILD_DATE='2023-01-01T01:01:01Z'
export GIT_COMMIT=123abcd
export GIT_TREE_STATE=dirty

# Main

exec skaffold ${ARGS}
