# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/engine.nagare.media_clusterfunctions.yaml
- bases/engine.nagare.media_clustermedialocations.yaml
- bases/engine.nagare.media_clustermediaprocessingentities.yaml
- bases/engine.nagare.media_clustertasktemplates.yaml
- bases/engine.nagare.media_functions.yaml
- bases/engine.nagare.media_medialocations.yaml
- bases/engine.nagare.media_mediaprocessingentities.yaml
- bases/engine.nagare.media_tasks.yaml
- bases/engine.nagare.media_tasktemplates.yaml
- bases/engine.nagare.media_workflows.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_clusterfunctions.yaml
- patches/webhook_in_clustermedialocations.yaml
- patches/webhook_in_clustermediaprocessingentities.yaml
- patches/webhook_in_clustertasktemplates.yaml
- patches/webhook_in_functions.yaml
- patches/webhook_in_medialocations.yaml
- patches/webhook_in_mediaprocessingentities.yaml
- patches/webhook_in_tasks.yaml
- patches/webhook_in_tasktemplates.yaml
- patches/webhook_in_workflows.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_clusterfunctions.yaml
- patches/cainjection_in_clustermedialocations.yaml
- patches/cainjection_in_clustermediaprocessingentities.yaml
- patches/cainjection_in_clustertasktemplates.yaml
- patches/cainjection_in_functions.yaml
- patches/cainjection_in_medialocations.yaml
- patches/cainjection_in_mediaprocessingentities.yaml
- patches/cainjection_in_tasks.yaml
- patches/cainjection_in_tasktemplates.yaml
- patches/cainjection_in_workflows.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

patchesJson6902:
# patches here fix missing x-kubernetes-map-type
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: clustertasktemplates.engine.nagare.media
  path: patches/maptype_tasks.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: tasks.engine.nagare.media
  path: patches/maptype_tasks.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: tasktemplates.engine.nagare.media
  path: patches/maptype_tasks.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: clusterfunctions.engine.nagare.media
  path: patches/maptype_functions.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: functions.engine.nagare.media
  path: patches/maptype_functions.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
