namespace: nagare-media-engine-system

bases:
  - ../output-all

resources:
  - gateway-nbmp_ingress.yaml

patches:
  - path: patches/gateway-nbmp.yaml
  - path: patches/workflow-manager.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: gateway-nbmp-config
    behavior: replace
    files:
      - gateway-nbmp.yaml=gateway-nbmp_configuration.yaml
  - name: workflow-manager-config
    behavior: replace
    files:
      - workflow-manager.yaml=workflow-manager_configuration.yaml
