bases:
- ../default

patchesStrategicMerge:
- manager_patch.yaml
- gateway-nbmp_patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  behavior: replace
  files:
  - controller_manager_configuration.yaml
