---
apiVersion: engine.nagare.media/v1alpha1
kind: MediaLocation
metadata:
  labels:
    app.kubernetes.io/name: medialocation
    app.kubernetes.io/instance: s3
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/created-by: nagare-media-engine
  name: s3
spec:
  s3:
    bucket: nagare-media-engine
    region: us-east-1
    auth:
      aws:
        secretRef:
          name: s3-aws-auth
    endpointURL: http://minio.s3:9000/
    usePathStyle: true
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-aws-auth
type: Opaque
stringData:
  accessKeyID: MLYEAE6AES7IUSL4APYL
  secretAccessKey: snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H
# ---
# apiVersion: engine.nagare.media/v1alpha1
# kind: MediaLocation
# metadata:
#   labels:
#     app.kubernetes.io/name: medialocation
#     app.kubernetes.io/instance: rtmp
#     app.kubernetes.io/part-of: nagare-media-engine
#     app.kubernetes.io/created-by: nagare-media-engine
#   name: rtmp
# spec:
# TODO(mtneug): add "streaming" media location
