apiVersion: engine.nagare.media/v1alpha1
kind: ClusterFunction
metadata:
  labels:
    app.kubernetes.io/name: function
    app.kubernetes.io/instance: generic-sleep
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/created-by: nagare-media-engine
    beta.engine.nagare.media/function-type: generic
  name: generic-sleep
spec:
  version: 0.0.1
  template: # JobTemplate
    spec:
      template: # PodTemplate
        metadata:
          annotations:
            kubectl.kubernetes.io/default-container: function
        spec:
          restartPolicy: Never # recreate pod by job controller
          terminationGracePeriodSeconds: 35
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          containers:
            - name: function
              image: ghcr.io/nagare-media/engine/function-generic-sleep:dev
              imagePullPolicy: IfNotPresent
              ports:
                - name: stream-http
                  containerPort: 8080
                  protocol: TCP
                - name: task-api
                  containerPort: 8888
                  protocol: TCP
              startupProbe:
                failureThreshold: 60
                periodSeconds: 2
                httpGet:
                  path: /healthz
                  port: task-api
              readinessProbe:
                periodSeconds: 2
                httpGet:
                  path: /readyz
                  port: task-api
              livenessProbe:
                periodSeconds: 2
                httpGet:
                  path: /healthz
                  port: task-api
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  cpu: 10m
                  memory: 16Mi
            - name: workflow-manager-helper
              image: ghcr.io/nagare-media/engine/workflow-manager-helper:dev
              imagePullPolicy: IfNotPresent
              ports:
                - name: event-api
                  containerPort: 8181
                  protocol: TCP
              startupProbe:
                failureThreshold: 60
                periodSeconds: 2
                httpGet:
                  path: /healthz
                  port: event-api
              readinessProbe:
                periodSeconds: 2
                httpGet:
                  path: /readyz
                  port: event-api
              livenessProbe:
                periodSeconds: 2
                httpGet:
                  path: /healthz
                  port: event-api
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
