apiVersion: engine.nagare.media/v1alpha1
kind: ClusterMediaProcessingEntity
metadata:
  labels:
    app.kubernetes.io/name: mediaprocessingentity
    app.kubernetes.io/instance: edge-cluster
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/created-by: nagare-media-engine
  name: edge-cluster
spec:
  remote:
    kubeconfig:
      # this secret is created within the default namespace in the kind management test cluster during `make kind-up`.
      secretRef:
        namespace: default
        name: edge-cluster-kubeconfig
        key: kubeconfig
