apiVersion: engine.nagare.media/v1alpha1
kind: WorkflowManagerConfig
metadata:
  labels:
    app.kubernetes.io/name: workflowmanagerconfig
    app.kubernetes.io/instance: workflow-manager-config
    app.kubernetes.io/component: workflow-manager
    app.kubernetes.io/created-by: nagare-media-engine
    app.kubernetes.io/part-of: nagare-media-engine
    app.kubernetes.io/managed-by: kustomize
leaderElection:
  leaderElect: true
nats:
  url: nats://nats.nats.svc.cluster.local:4222
