apiVersion: batch/v1
kind: Job
metadata:
  name: upload-media
spec:
  template:
    spec:
      restartPolicy: Never # recreate pod by job controller
      containers:
        - name: upload
          image: minio/mc:RELEASE.2023-02-28T00-12-59Z
          command: ["/bin/sh", "-c"]
          args:
            - |
              mc config host add s3 \
                http://minio.s3.svc.cluster.local:9000 \
                MLYEAE6AES7IUSL4APYL \
                snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H \
                --api S3v4
              curl -sSL -o /tmp/sintel.mov https://public.educast.cloud/media/master/sintel.mov
              mc cp /tmp/sintel.mov s3/nagare-media-engine-tests/inputs/sintel.mov
