apiVersion: batch/v1
kind: Job
metadata:
  name: upload-media
spec:
  template:
    spec:
      restartPolicy: Never # recreate pod by job controller
      initContainers:
        - name: download
          image: alpine:edge
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              wget -O /data/caminandes-1-llama-drama.mp4 https://public.s3.shio.services/media/testing/full-caminandes-1-llama-drama.mp4
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: upload
          image: minio/mc:RELEASE.2024-08-17T11-33-50Z
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              mc config host add s3 http://minio.s3.svc.cluster.local:9000 MLYEAE6AES7IUSL4APYL snTrPIV2NDBoQOjpL10Nk6KY6EyWlePkF1NLMX3H --api S3v4
              mc cp /data/caminandes-1-llama-drama.mp4 s3/nagare-media-engine-tests/inputs/caminandes-1-llama-drama.mp4
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
