name: container-images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        if: ${{ github.event_name == 'push' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x

      - name: build and push container images
        run: |
          case "${{ github.event_name }}" in
            push)  BUILDX_OUTPUT='--push' ;;
               *)  BUILDX_OUTPUT=''       ;;
          esac

          make image \
            IMAGE_PLATFORMS=linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x \
            BUILDX_OUTPUT="${BUILDX_OUTPUT}"
